### ISSUE TITLE
switch..case.. in structure throws error

### ISSUE THREAD

**Issue by toolwtech** [m4rs-mt/ILGPU#100]
@m4rs-mt 
Please see attached sample code.  The simple structure causes problem with the lasted version of ILGPU (beta3.0).  There was no problem with old version (0.7, 0.8.0).  If you decrease "case" in switch, e.g. only keep 3 cases (0,1,2), then there is no problem with beta3.  Instead of using "switch..case..", It seems that one or multiple array (fixed array) in structure is really needed for more efficient and flexible code.  
[SimpleStructures.zip](https://github.com/m4rs-mt/ILGPU/files/4607200/SimpleStructures.zip)

**Comment by m4rs-mt** [comment]
@toolwtech Thank for submitting this issue. It seems to be a problem related to the Cuda PTX assembler and not the code emitted by ILGPU.

Additional remarks: based on the sample you have provided, it looks like you are trying to handle multiple grid cells with inline neighbor lists. Please note that your structure will have a bad memory layout when processing multiple grid cells in parallel since the data-stride between multiple grid cells is really large. When you change the underlying data layout to a SOA version, you can easily work around all switch cases constructions and even improve performance significantly in general 🤓 Furthermore, there are much more efficient ways of realizing a neighbor lookup on GPUs for multiple grid cells.  You might want to take a look into [this implementation](http://www.fluids3.com/) which does not require a single inline data storage for structures with nested arrays.

**Comment by toolwtech** [comment]
@m4rs-mt  Thanks for your suggestion!  I am trying to put array in struct and create SOA, but it seems that ILGPU doesn't support array in struct, it also doesn't support fixed array in struct.  Please see attached sample code.  How can we implement SOA without ILGPU's support of array in struct. Straight array may be a choice, but the downside is poor readability.

**Comment by toolwtech** [comment]
[SimpleStructures.zip](https://github.com/m4rs-mt/ILGPU/files/4612742/SimpleStructures.zip)
