### ISSUE TITLE
Support for Span<T>/Memory<T>?

### ISSUE THREAD

**Issue by matthew-a-thomas** [m4rs-mt/ILGPU#122]
Is it possible to convert an `ArrayView<byte>` into a `Span<byte>` or a `Memory<byte>`? (Without a naive block copy)

If not, have you considered adding this support? I suspect it might be possible with a custom [`MemoryManager`](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.memorymanager-1?view=netcore-3.1).

The motivation is easier integration with framework code. Many things (string decoding, SHA hashing, etc) can use `Span` to reduce allocations / improve speed.

Thanks!

**Comment by matthew-a-thomas** [comment]
Glancing at your source code, I think this would certainly be possible. You're already dealing with a raw pointer here:
https://github.com/m4rs-mt/ILGPU/blob/master/Src/ILGPU/ArrayView.cs#L194

All that remains is to package that pointer up (with the length) into a `Memory<byte>` through a custom `MemoryManager`. The [`MemoryMarshal`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.memorymarshal?view=netcore-3.1) class can then take care of quickly casting from `Span<byte>` to `Span<T:unmanaged>`.

I have a little bit of experience with this kind of thing. One time I used a custom `MemoryManager` with [`MemoryMappedFile`](https://docs.microsoft.com/en-us/dotnet/api/system.io.memorymappedfiles.memorymappedfile?view=netcore-3.1) to provide byref access to bytes on disk (with minimal allocation; certainly without having to marshal bytes).

**Comment by m4rs-mt** [comment]
@matthew-a-thomas Thank you for your feature request. The short answer is yes, it makes sense to add support for these types in the future. However, you should be very careful when converting an `ArrayView<T>` instance to a `Memory<T>` (or `Span<T>`) instance, because direct memory accesses only work in the case of the `CPU Accelerator`. In addition, passing `Memory<T>` or `Span<T>` instances to a kernel requires a kernel-launcher extension to convert these types to GPU and runtime compatible launcher code.

**Comment by MoFtZ** [comment]
> However, you should be very careful when converting an `ArrayView<T>` instance to a `Memory<T>` (or `Span<T>`) instance, because direct memory accesses only work in the case of the `CPU Accelerator`. In addition, passing `Memory<T>` or `Span<T>` instances to a kernel requires a kernel-launcher extension to convert these types to GPU and runtime compatible launcher code.

@m4rs-mt What about adding `Span<T>` and `Memory<T>` support to `ExchangeBuffer<T>`? The user can then read/write from the pinned memory block that exists on the CPU-side.

This would hopefully be easier to use that the existing `ExchangeBuffer<T>.CPUView` properties, or index operator.

It would also avoid the complexity of implementing kernel support for `Span<T>` and `Memory<T>`.

**Comment by m4rs-mt** [comment]
@MoFtZ this would be a nice place to extend. This should simplify the general IO pipeline with respect to `Span<T>` and `Memory<T>`.

**Comment by Yey007** [comment]
Since I have already worked on the `ExchangeBuffer<T>` class (now split up into multiple classes), I could try taking this on. Is anyone already working on this?

**Comment by Yey007** [comment]
One question on the implementation though, should `Memory<T>` contain a copy of the data or point to the same location? Currently it's a bit difficult to not end up copying with the constructor provided, that's why I'm asking. I'm sure it can be done without copying, it's just gonna take me longer because I have to do some "research".

**Comment by Yey007** [comment]
So the PR added this functionality to the` ExchangeBuffer`, but do we still want to add this to `ArrayView` or `MemoyBuffer`? From what I understand, `ArrayView` and `MemoryBuffer` live on the GPU so this may not work. Someone can correct me on that if I'm wrong.
