### ISSUE TITLE
ILGPU.Runtime.Cuda.CudaException: 'unknown error'

### ISSUE THREAD

**Issue by Aphexus** [m4rs-mt/ILGPU#13]
Just installed ILGPU to test out and get that error. I was getting this error:
"a PTX JIT compilation failed"

and so I updated the Nvidia drivers to latest. Then I got the titled error at this line:

using (var accelerator = Accelerator.Create(context, acceleratorId))

Seems to happen on most projects if not all. Cannot proceed to test out ILGPU.

**Comment by m4rs-mt** [comment]
@Aphexus The error message "a PTX JIT compilation failed" indicates a broken kernel. This error message cannot (or should not - in theory) appear during accelerator initialization. The "unknown error" you are referring to indicates a kernel-driver initialization issue that is reported by the (broken?) graphics driver. This error can appear during accelerator initialization if the driver cannot create a valid context handle and pass this handle to the ILGPU runtime. However, I need much more information about your system: driver version, operating system, target platform configuration of your project (is 'prefer 32bit' disabled?), number of accelerators, ILGPU version, is an SLI-connector involved? etc.

You mentioned that `Accelerator.Create(context, acceleratorId)` raises this exception. Consequently, the following code should not trigger the problem:
```
using (var context = new Context())
{
	// Without accessing any accelerator
}
```
I'm asking because `new Context()` already initializes all basic driver interfaces and queries all available GPUs (in version 0.5).

**Comment by m4rs-mt** [comment]
I close this issue for now because of inactivity; it can be reopened at any time.

**Comment by NoUDerp** [comment]
Installing the drivers directly from nVidia (instead of the default Windows update drivers) fixed this for me.
