### ISSUE TITLE
Is RadixSort of signed double way slower than signed long?

### ISSUE THREAD

**Issue by toolwtech** [m4rs-mt/ILGPU#184]
or they are close given a large number of data set

**Comment by m4rs-mt** [comment]
@toolwtech Thank you for posting your question here. In general, a `double` value is always signed, because it carries a "sign bit". Also note that a comparison between two double values is usually more expensive than a comparison of 64bit integer values.

However, since RadixSort sorts bits rather than comparing values, the "meaningful" bits have to extracted from the floating-point numbers ([this article](http://codercorner.com/RadixSortRevisited.htm) gives an introduction). Consequently, I wouldn't expect the runtime to be significantly slower when sorting `doubles` instead of `longs`.

**Comment by toolwtech** [comment]
@m4rs-mt Thanks! I will have a try if speed is close.  I truncated and converted float to long to sort float before with sacrifice of accuracy
