### ISSUE TITLE
Any example code for parallel computing using multiple GPU (specifically multiple Nvidia) ?

### ISSUE THREAD

**Issue by toolwtech** [m4rs-mt/ILGPU#197]
It would be great if any example code can be provided in ILGPU example project for parallel computing using multiple GPUs  (e.g. several Nvidia accelerators) so that we can explore the potential multiple GPUs parallel.

**Comment by MoFtZ** [comment]
@toolwtech In order to use multiple GPUs, you need to create multiple accelerators. Each Cuda accelerator is assigned a Device ID by the Cuda framework, starting from 0 and incrementing by 1.

```CSharp
var context = new Context();
var accelerator1 = new CudaAccelerator(context, 0);
var accelerator2 = new CudaAccelerator(context, 1);
```

**Comment by toolwtech** [comment]
Can Kernels created in accelerator2 directly use data Buffer created in accelerator1?  or How to share data Buffer between multiple accelerators?

**Comment by MoFtZ** [comment]
I have used multiple GPUs, but have not tried to share data or transfer data between them.

In theory, you should be able to pass the memory buffer from one accelerator as a parameter to another accelerator. Note that this maybe not be very performant because GPU 1 will access the data on GPU 2 via the CPU.

This should be faster if you have NVLINK between your GPUs, enabling direct access and transfers.

You may also need to `EnablePeerAccess` as [previously mentioned](https://github.com/m4rs-mt/ILGPU/issues/154).
