### ISSUE TITLE
Create a Cuda stream without CU_STREAM_NON_BLOCKING

### ISSUE THREAD

**Issue by samy2** [m4rs-mt/ILGPU#222]
Hi ILGPU Team,

Thank you again for this amazing library!

I had a problem when I tried to upgrade my app from ILGPU 0.7.1 to 0.8.1
My app is creating a cuda stream with ILGPU, uses ILGPU kernels to compute some data, and then invokes the Nvidia TensorRT library, using the same cuda stream, to execute a neural network calculation with the calculated data as input.

The problem was that the results were wrong after migrating to ILGPU 0.8.1.. but after extensive tests, all the ILGPU kernels were working correctly... After some headache, I discovered that there seems to be a bug in TensorRT, in some cases, when the cuda stream is created with the CU_STREAM_NON_BLOCKING option. (see https://forums.developer.nvidia.com/t/ssd-with-non-blocking-stream/74039)

With ILGPU 0.8.1, there is no obvious way to create the cuda stream without the CU_STREAM_NON_BLOCKING option. Could this functionality be exposed in a future version ?

(For the moment, I worked-around by creating the cuda stream with ManagedCuda, and invoking by reflection the internal constructor CudaStream(Accelerator accelerator, IntPtr ptr))

**Comment by m4rs-mt** [comment]
@samy2 Thank you for submitting this issue report. Oh wow, this is really unfortunate, because a `Stream` in ILGPU had been designed to perform async operations. I guess it makes sense to include this option in order to give developers the opportunity to change the underlying behavior of a `CudaStream`. This should avoid further issues in the future related to different stream properties.

However, I would recommend that we add an additional constructor overload to expose this functionality. The default setting should still remain `CU_STREAM_NON_BLOCKING`.
