### ISSUE TITLE
A question regrading performance and consumed resources

### ISSUE THREAD

**Issue by GeoBIM2020** [m4rs-mt/ILGPU#226]
I have a question regrading performance and consumed resources: which kernel (kernel1 or kernel2) is faster and uses less resources in following code? assuming "Test" contains lots of fields besides X and Y involved in calculation, does kernel2 load all of its fields and consume many more registers/resources with calling "calculate(..)" ?  

Thanks!

struct Test
{
   public double X;
   public double Y;
   public double Z;
   public double W;
   public double W1;
   public double W2;
   ...
   ...
   ...   //many more fields
   ...
   ...
   public double Calculate(double val)
   {
        return X+Y+val;
   }
}

static void Kernel1(Index1 index, ArrayView<Test> dataView, double val, ArrayView<double> output)
{
       ref Test data = ref dataView[index];
       output[index] = data.X+data.Y+val;
}

static void Kernel2(Index1 index, ArrayView<Test> dataView, double val, ArrayView<double> output)
{
       ref Test data = ref dataView[index];
       output[index] = data.Calculate(val);
}

**Comment by MoFtZ** [comment]
@toolwtech
The overhead of calling a method on the GPU is comparable to calling a method on the CPU. Yes, it will consume more resources to call a method. However, in general, the difference in performance and resources is negligible - this is true on both the CPU and GPU.

If you are calling a method many many times in a loop, the costs will add up. If your method is large and complex, the extra overhead of the method call will probably be irrelevant, because your large and complex method will consume much more time and resources. Again, this is true on both the CPU and GPU.

In the example you provided, the method was very short. In this case, compilers in general, and ILGPU in particular, will automatically inline the method. 

When I created a sample program based on the example you supplied, using ILGPU v0.8.1.1, the PTX generated for `Kernel1` and `Kernel2` were identical - because it was automatically inlined. However, if the `Calculate` method is very large and complex (or if I add the `[MethodImpl(MethodImplOptions.NoInlining)]` attribute), then ILGPU will generate a separate PTX method.

**Comment by toolwtech** [comment]
@MoFtZ Thanks for your detailed explanation! The reason I was asking for this kind of question is that I have a complex method and I have to use AutoGroupedKernel like Kernel2, kernel throws exception (too many resources) otherwise if I use implicitly grouped kernel. At this point, I want to ask a relevant question about memory type in the method of kernel2.  In method of "Calculate" in kernel2, I define following variables in order to store some of those data (e.g. X and Y) in global memory to register or local memory to speed up calculation:
double v1 = X;
double v2 = Y;
are v1 and v2 stored in register memory or local memory with PTX generation?   or are X, Y and all of other fields in "Test" automatically stored in register or local memory as the method is called in the kernel even if without above variables (if so, defining above variables is totally unnecessary)?

**Comment by MoFtZ** [comment]
@toolwtech The PTX compiler supplied by Nvidia will automatically store values into registers. And, once it has run out of registers, it will 'spill' the remaining values to local memory.

If you want to declare local variables like `v1` and `v2` for easier maintenance of your code, that's fine - it should consume the same number of registers or local memory.

**Comment by m4rs-mt** [comment]
@GeoBIM2020 FYI we have added extended kernel compilation information objects in #383 (the upcoming v1.0 release) that allow you to get more information about the kernels compiled by ILGPU (e.g. the amount of local memory used).

I am closing this issue for now due to inactivity.
