### ISSUE TITLE
a problem about the SimpleStructures samples

### ISSUE THREAD

**Issue by huiyiyuxin** [m4rs-mt/ILGPU#231]
Thank you for the powerful library. 
I Meet with a problem.
 when I run the "SimpleStructures" samples, I get such errors. 
How could I solve it.
Best Wishes.
![image](https://user-images.githubusercontent.com/28803563/89603503-de571180-d89b-11ea-9c8b-cf6fc78d0a54.png)

**Comment by MoFtZ** [comment]
hi @huiyiyuxin. The sample code will try to run on each Accelerator on your computer. Do you know which accelerator is failing? Also, are all the accelerators failing or just some of them?

There is a CPU accelerator, which uses your CPU to emulate the GPU.
The Cuda accelerator is used by Nvidia graphics cards.
The OpenCL accelerator is used by AMD graphics cards, and some CPUs also provide support for OpenCL.

It might be a good idea to ensure you have the latest drivers.
From my experience, the OpenCL accelerator for my CPU had a number of issues before updating to the latest driver. Also, it only provides limited support for all the features of ILGPU.

**Comment by m4rs-mt** [comment]
hi @huiyiyuxin. This error message can be related to the fact that the ILGPU runtime library cannot access the `CustomDataType` in the project. We have added the assembly attribute `[InternalsVisibleTo(...)]` to the sample projects in order to make all internal types visible to the runtime library. Is it possible that in your case the attribute was not compiled correctly/not added to the project?

**Comment by huiyiyuxin** [comment]
Dear m4rs-mt and MoFtZ， Thank you  for your help, I added the assembly attribute to the projects, and it can work at CPU. Best Wishes
