### ISSUE TITLE
Invalid Accelerator synchronization in OpenCL

### ISSUE THREAD

**Issue by m4rs-mt** [m4rs-mt/ILGPU#240]
The current implementation of `CLAccelerator.Synchronize` synchronizes the default accelerator stream only. However, the intended behavior would be to synchronize all accelerator streams (like in the case of the `CPUAccelerator` and the `CudaAccelerator`).

Steps to reproduce:
```c#
var stream = Accelerator.CreateStream();

// ...

kernel(stream);

// ...

Accelerator.Synchronize(); // Will not be synchronized here
```

**Comment by Yey007** [comment]
The issue appears to stem from these lines in `CLAccelerator`:

```
/// <summary cref="Accelerator.Synchronize"/>
protected override void SynchronizeInternal() =>
       DefaultStream.Synchronize();
```

**Comment by Yey007** [comment]
The fix for this should (hopefully) be relatively easy, as long as we can either

1. Find a native method that already does this (what does it even mean to synchronize a CL queue?)
2. Find a way to get all streams bound to an accelerator. This may already exist in ILGPU or we may have to add a private `List` of streams.

**Comment by MoFtZ** [comment]
@Yey007 The OpenCL functions for reading/writing buffers requires a command queue (`clEnqueueReadBuffer`, `clEnqueueWriteBuffer`). In theory, you should be able to use `Stream.Synchronize()` (internally calling `clFinish`) to wait for the stream to complete.

My initial thoughts are we would need the accelerator to maintain a list of streams, because there is no global synchronisation. But we also need to be careful, because the streams implement IDisposable.

**Comment by m4rs-mt** [comment]
@Yey007 @MoFtZ It makes sense to maintain a list of streams to synchronize. However, the `Accelerator` instance maintains a list of non-disposed child-objects via `WeakReference` associations (`childObjects`, see [here](https://github.com/m4rs-mt/ILGPU/blob/master/Src/ILGPU/Runtime/AcceleratorObject.cs#L108)). We could use this list to resolve the actually "active" streams and synchronize them. However, we need to be careful to not interfere with the custom Accelerator GC [implementation](https://github.com/m4rs-mt/ILGPU/blob/master/Src/ILGPU/Runtime/AcceleratorObject.cs#L194).

Maybe there is another non-obvious OpenCL trick to link streams to events and wait for them?

**Comment by Yey007** [comment]
I don't exactly understand the problem with the GC. It removes unused objects from the list, so there shouldn't be anything left over that was disposed of, right?

**Comment by Yey007** [comment]
Additionally, can't we just use something like `WeakReference.IsAlive` to make sure we're not messing with something that isn't there?

**Comment by m4rs-mt** [comment]
@Yey007 there is no particular problem with our Accelerator GC. I just wanted to note that we have to take concurrency into account while iterating over the list 🤓

**Comment by Yey007** [comment]
Alright, I'll try to get working on this.
