### ISSUE TITLE
Thank you very much for the library provided by the author. My program is ready to run, but it needs large memory. I'm trying to adjust the code.

### ISSUE THREAD

**Issue by xxl-cc** [m4rs-mt/ILGPU#257]
Can there be a more detailed example of the ExchangeBuffer？Is pinned memory zero-copy?

**Comment by m4rs-mt** [comment]
@xxl-cc We can provide an example demonstrating the use of the `ExchangeBuffer` class 🤓 The "only thing" you need to do is to allocate an `ExchangeBuffer` instance like a default memory buffer. Afterwards, you can use the `CopyToAccelerator` and `CopyFromAccelerator` methods to transfer data between the CPU and GPU buffers. Use the appropriate View-getters to access the CPU/GPU memory buffers stored inside the `ExchangBuffer`:

```c#
            // Write data into the CPU part
            var cpuView = buff.Span;
            // ...
            buff.CopyToAccelerator();

            // Use GPU data
            var gpuPart = buff.View;

            // Load GPU data
            buff.CopyFromAccelerator();
```

Regarding your question about zero-copy: There is currently no support for pinned-memory based zero-copy buffers.

**Comment by Yey007** [comment]
Zero-copy does sound like a good thing to add to `ExchangeBuffer` in the future though. I'm not sure if ti would be possible with the current architecture, but maybe if we write some zero-copy `MemoryBuffer`-like classes?

Thoughts?

**Comment by binaryalgorithm** [comment]
I was interested in this too. CUDA calls it unified memory (so that explicit copy doesn't need to happen - instead pointers are shared between CPU/GPU after buffer mapping). In OpenCL it is called rather SVM Buffer (shared virtual memory). I recently upgraded to an OpenCL 2.0 device but I haven't ever tried to use this functionality in C#. I think you have to take care to pin the buffer memory in C#, but this could perhaps be taken care of with a particular kind of ILGPU buffer type? I don't think this is covered in any of the example code samples (there is "shared memory" example but it appears to be the GPU allocated kind).

**Comment by m4rs-mt** [comment]
I am closing this for note as there have been a lot of discussion about this in the Discord channel and this topic seems to be inactive at the moment.
