### ISSUE TITLE
GetRowView strange behavior

### ISSUE THREAD

**Issue by Aleksey1555** [m4rs-mt/ILGPU#330]
Hello.
I write this code:
```c#
Context cntx = new Context();
CudaAccelerator ca = new CudaAccelerator(cntx);
int [,]a = new int[,] { { 10, 20 }, { 30, 40 } };
MemoryBuffer2D<int> mb = ca.Allocate<int>(a);
ArrayView<int> res= mb.GetRowView(0);
```
and the res is [10,30]
How can it be?
I mean that - 0 row index must return array of [10,20] !
but as you can see, it return's [10,30].
Maybe this is the error?

And if set 1 to GetRowView, like this:
`ArrayView<int> res= mb.GetRowView(1); `
this return error **"invalid argument"**

Is this some kind of error?
Please answer

**Comment by m4rs-mt** [comment]
@Aleksey1555 Thank you for submitting this issue and welcome to the ILGPU community. The reason why you receive "10, 30" is the fact that all `X`-dimension values are stored consecutively in memory: "10, 30, 20, 40". This mimics the "default" computer graphics behavior, which expects all `X`-dimension values to be stored after each other in memory.

Regarding your "invalid argument" issue: I am able to execute the following kernel using `GetRowView(0)` and `GetRowView(1)` without any problems:
```c#
static void WriteToView(Index1 index, ArrayView<int> data)
{
    data[index] = 42;
}
...
ArrayView<int> res2 = mb.GetRowView(1);
ca.LaunchAutoGrouped(WriteToView, ca.DefaultStream, new Index1(res.IntLength), res2);
...
```

 However, I have recognized that the debugger view of the second array view does not seem to work properly, as it displays "CUDA_INVALID_ARGUMENT" in the debugger. Please note that this does not affect the functionality of the program 🤓. You can always inspect the main `MemoryBuffer2D` in the debugger and/or access the results on the CPU by fetching them using `GetAsArray`.

**Comment by Ruberik** [comment]
@m4rs-mt Does that mean that when you call ca.Allocate, it reorders the contiguous chunk of memory? Is there a way to disable that behaviour?

**Comment by MoFtZ** [comment]
@Ruberik yes, for multi-dimensional arrays, ILGPU will re-order the elements when copying to/from the GPU.

Internally, ILGPU is re-ordering those elements into a linear array. This linear array is then supplied to the GPU drivers.

To workaround the re-ordering, you can use a linear array. Then, use the functions like `As2DView` to re-interpret the linear view as a multi-dimensional view.

**Comment by Ruberik** [comment]
Thanks for the workaround suggestion; you're right that it could work, though of course both the way it's implemented now and the workaround are slower than copying the data in the order it was already in.

I gather it's fairly common among GPU libraries to have a flag to choose the behaviour here. Is that something that exists, or that you'd consider adding? My reasoning follows.

I care about memory locality. I have an array in C# as `arr[x,y]` because I want to be able to iterate through `arr[x,i]` for some fixed `x` and all values of `i`, and have that be local. If I call `MemoryBuffer2D<int> mb = ca.Allocate<int>(arr);` then two things are happening that I don't want:

1. The memory copy is slower than it needs to be, because of the re-ordering process you described.
2. The thing I chose to have memory locality doesn't anymore. Instead, something I don't care about has memory locality.

To work around this, I need to use a similarly slow memory copying process, then reverse the order of my indexes. So `x[batchId, subBatchId, iterationId]` becomes `xView[iterationId, subBatchId, batchId]`. Semantically that doesn't look good to me, but perhaps it would look good to someone who deals with computer graphics, so I can't claim moral superiority there. :-)

**Comment by Ruberik** [comment]
By the way, I ended up working around the reordering by manually transposing the array. Now it gets transposed twice, and I get the locality I want (albeit with the indexing I don't want). I don't think it's a great solution, but... that's why they call it a workaround!

**Comment by Aleksey1555** [comment]
Thanks for answers!

**Comment by m4rs-mt** [comment]
@Ruberik @Aleksey1555 I have started a new discussion about row-major and column-major data layouts in #346. We can continue the discussion in this thread.
