### ISSUE TITLE
Provide Simple Matrix Multiplication kernel?

### ISSUE THREAD

**Issue by faruknane** [m4rs-mt/ILGPU#34]
Hi, first of all I want to thank you for all you've done! 

I've decided to use ILGPU in [my deep learning library project](https://github.com/faruknane/DeepLearningFramework). I hope it is as fast as c++ cuda. Except compiling time, I believe that it doesn't have any latency while accessing gpu, which was the issue I am so afraid of. I made a couple tests for this.

I am still confused if I should use ILGPU, because @m4rs-mt didn't provide some basic kernels I don't know how to improve my code. I want to know how to improve the performance of SGEMM. Can you provide at least simple Matrix Multiplication kernel? I need to benchmark against CUBLAS and try to improve the performance.

**Comment by faruknane** [comment]
For example:

```csharp
static void MyKernel(
            ILGPU.Index index, ILGPU.Index index2,               // The global thread index (1D in this case)
            ArrayView<float> dataView, ArrayView<float> dataView2,   // A view to a chunk of memory (1D in this case)
            int constant)              // A sample uniform constant
        {
            dataView[index] += index+index2;
            dataView2[index2] += index + index2;
        }
```
does this method iterate index and index2 independently meaning it works index * index2 times.

**Comment by m4rs-mt** [comment]
@faruknane Thank you very much for your feedback. Your project looks quite interesting.

`I am still confused if I should use ILGPU, because @m4rs-mt didn't provide some basic kernels I don't know how to improve my code`

I'm afraid I don't fully understand your point here. Did you take a look at the [sample repository](https://github.com/m4rs-mt/ILGPU.Samples) or the [documentation](http://www.ilgpu.net/Documentation)? There are several basic kernels and use cases that show how to use the library in an appropriate way to get started. If you want to write a matrix multiplication kernel, you can refer to a [sample implementation](https://www.quantstart.com/articles/Matrix-Matrix-Multiplication-on-the-GPU-with-Nvidia-CUDA) and convert the kernel to the ILGPU world based on the kernels in the sample repository. However, I totally agree that in the near future we should add such a simple kernel to the sample repository to simplify the process of "getting used to the library".

**Comment by MoFtZ** [comment]
Added sample project in https://github.com/m4rs-mt/ILGPU.Samples/pull/5

**Comment by faruknane** [comment]
Thank you so much guys. Appreciate it!

**Comment by m4rs-mt** [comment]
Thanks to @MoFtZ we can now close this ticket 🥇
