### ISSUE TITLE
Row-/Column-major data layouts and the .Net array interop

### ISSUE THREAD

**Issue by m4rs-mt** [m4rs-mt/ILGPU#346]
ILGPU provides built-in 2D and 3D memory buffers (`MemoryBuffer2D` and `MemoryBuffer3D`) and the associated array views (`ArrayView2D` and `ArrayView3D`). They "use" a row-major data layout that perfectly matches the fastest varying indices (FVI) in the scope of GPU kernels (based on `Index3` and and the "default" way of computing global thread indices in Cuda, OpenCL, OpenGL Compute and DirectX Compute). Consider the following piece of code demonstrating the "standard" way of computing a global linear index in memory using a 1D grid of 1D blocks and a 3D grid of 1D blocks:
```c++
__device__ int getGlobalIdx_1D_1D(){
    return blockIdx.x *blockDim.x + threadIdx.x;
}

__device__int getGlobalIdx_3D_1D(){
    int blockId = blockIdx.x + blockIdx.y * gridDim.x
        + gridDim.x * gridDim.y * blockIdx.z;
    int threadId = blockId * blockDim.x + threadIdx.x;
    return threadId;
}
```
Refer to the `simpleIndexing.cu` sample in the Cuda samples directory for more information. The ILGPU index types are structured in the same way, so that Graphics and GPGPU developers can easily benefit from the same "multidimensional index" to "linear index" mapping. The analogy is always: we start processing from the top-left corner of a 2D image and move downwards line by line (or row by row).

However, there are several `CopyFrom` and `GetAsXDArray` functions that consume or return multidimensional arrays of the form `T[,,]`. They currently transpose the input/output arrays. This is due to the reason that `cpuData[x, y]` is intended to be accessible via `gpuData[x, y]`:
```c#
// Setup .Net array buffer
var buff = new int[1024, 4];
buff[17, 2] = 42;

// Initialize GPU buffer
using var t = accl.Allocate(buff);
// Width = 1024
// Height = 4

// Would also yield 42 on a GPU
// int data = t.View[17, 2];

// Yields also 42
var buff2 = t.GetAs2DArray();
int val = buff[17, 2];
```

What do you expect from the `CopyFrom` and `GetAsXDArray`? Shouldn't they transpose the memory layout and use the "raw" underlying .Net layout? In this case a 2D .Net array with `GetLength(0) = 1024` ("DimX") and `GetLength(1) = 4` ("DimY") would be converted to a `MemoryBuffer2D` instance with `Width = 4` and `Height = `1024`.

On the one hand, I am definitely not convinced that we should do this in general by taking the FVI of kernel thread indices into account. On the other hand, we have already received many questions about the semantics of these functions.

What do you think?

**Comment by Ruberik** [comment]
Thank you for starting this discussion! I understand the situation a lot better than I did back in our other thread, but please take this as only moderately-informed opinion and an attempt to structure the conversation.

There are three competing desires here, all of which are good and any two of which we can have:

1. Indexing is the same on the GPU as on the CPU.
2. Memory locality is the same on the GPU as on the CPU.
3. Arrays are indexed on the GPU in standard X,Y,Z ordering, where X is the least significant bit, and thus ranges of X have memory locality.

So some possibilities are:
1. 1&3: What ILGPU does right now. Transpose the array, and lose memory locality. The transposition and the loss of locality are bad for people who care about performance, which seems bad; why would you be using your GPU in C# if you didn't care about performance?
2. 1&2: Internally, maybe you make indexes go Z,Y,X instead of X,Y,Z. No transposition, no loss of locality. Potentially a weird experience for those who have done GPU programming elsewhere.
3. 2&3: No transposition. Confusing for newbies, who have to learn that x[i,j] == xView[j,i].
4. Control index order with a flag. My understanding is that this is functionality some other libraries offer. In other words, you get to keep memory locality and avoid transposing (my top two priorities), and users can decide how they want the indexes to work.

If I had to order the possibilities, I'd order them 4, 3, 2, 1. But I don't know how hard option 2 is, so I don't know how hard option 4 is.

My suggested immediate approach: Add functions, with different names, that allocate without transposing. Anybody who calls one of those should know that the order of the indices changes.

**Comment by yuryGotham** [comment]
I agree that cpuData[x, y] being accessible via gpuData[x, y] is good for ease of reading and comparing code.

However, I care about performance. I would love to have an option to call Allocate() and GetAs2DArray() in such a way that memory is copied over as a continuous block.

When I have a 2D dataset that would be worked on both in CPU and in GPU, I want to arrange the data in a way that creates as much locality in my memory access as possible. It is generally the same layout (in memory) in both CPU and GPU. I'm forced to use the ZYX in CPU and XYZ in GPU to get the performance and that's OK.

ILGPU currently does not have an easy way for me to move my multidimensional array between CPU and GPU. I'm forced to define an intermediate buffer and more my data twice (CPU->buffer->GPU or GPU->buffer->CPU). I give up some performance because of that, but it is not nearly as bad as having bad memory locality. Of course there is something that can be done here - you could introduce an option to transfer multidimensional arrays as a continuous block of memory. Such a feature would make my code to move the data between CPU and GPU a lot simpler AND it will run faster...

**Comment by m4rs-mt** [comment]
Finally getting back to this topic (after vacation and some feature PRs 😄🚀). I had several more discussions with various people on the web and @jgiannuzzi, @Joey9801 and @GPSnoopy about additional possible "solutions" to this problem. I also greatly appreciate the contributions of @Ruberik and @yuryGotham, their advice, opinions and hints. Based on this feedback, I spent several hours playing around with possible implementations (and how they would actually "feel" if we were to use them in practice).

@Joey9801 also pointed out that we should take a closer look at the `numpy`-method for representing various data layouts/padding/stride configurations without touching the actual data elements in memory. Representing such functionality within the ILGPU library might require a fundamental refinement of the multi-dimensional `ArrayView` types. However, this would allow us to express transposition operations in `O(1)` and use, for example, 2D array views with a user-defined alignment per row.

In C# code terms, an `ArrayView<T, TIndex>` can become an `ArrayView<T, TDimension or TShape>` structure, where `TDimension/TShape` specifies "how to linearize a given TIndex into a linear int/long index". In other words, a 2D dimensional array view could be implemented via
```c#
readonly struct Dimension2D (or Shape2D ?)
{
    public long Dim0 { get; } // Old Width = number of elements per column/row
    public long Dim1 { get; } // Old Height = number of elements per column/row

    public long Stride0 { get; } // = padded/algined number of elements/bytes? per column/row
    public long Stride1 { get; } // = padded/algined number of elements/bytes? per column/row

    public long ComputeElementIndex(Index2 index)
    {
        return index.X * Stride0 + index.Y * Stride1;
        // Instead of the "fixed" current layout: index.Y * Dim0 + Index.X
    }
}
```

This would add an additional (small) overhead at runtime. However, based on ILGPU's dynamic specialization features we could add a feature to specialize for specific dimensions/shapes for kernel arguments (possible specialization extension):
```c#
void Kernel(SpecializedArrayView<int, Dimension2D> arrayView)
{
    ...
    arrayView.Dimension // Known at kernel compile time
    arrayView[myIndex] // Will be resolved at runtime using constant values for Stride0 and Stride1
}
```

**Comment by GPSnoopy** [comment]
IMHO There are several problems (or standards) to be decided here, and how they relate to one another. And it's easy to confuse one with the other. Here are some of my thoughts and preferences.

## Multi-Dimensional Access using C#

AFAIK multi-dimension arrays are purely a C# concept that is not found in CUDA. In C CUDA, multi-dimensional accesses are still all done via single pointer and it's left to the user to do the correct pointer arithmetic wrt thread index and block dimensions. 

CUDA is neither row-major nor column major when accessing data through a single pointer. Only the multi-dimensional memory allocation methods matters (as a user, you need to know which dimension will end up being contiguous in memory on the GPU).

When programming in C#, accessing a multi-dimensional array with `values[k, j, i]` the `i` index is the one contiguously accessing memory, whereas `j` will be single strided and `k` "double" strided. What makes it easy for me as a programmer is knowing that it is always the last dimension that is the one that matters and needs to be in the inside loop.

Moving to ILGPU, I would prefer for `ArrayView3D` to reflect the same ordering, such that `view3D[k, j, i]` would need `threadIdx.x` to be mapped directly to `i` to have a contiguous memory access on the GPU. Because that's the one I've grown to understand in C#: the right-most index matches the contiguous memory layout.

I find the idea of `view3D[i, j, k]` (or `view3D[x, y, z]`) to be terribly confusing as it goes against the C# memory locality standard, I don't want to have to learn an ILGPU memory layout standard. It seems to be also the reason why you find yourself having to transpose memory when copying -> Bad.

**Preference**: given that CUDA has no multi-dimensional access notation and layout, keep the C# one.

## Row Major, Column Major and "Pixel" Major CUDA APIs

Where it gets really confusing is that the memory allocation routines in CUDA are expressed in terms of `width`, `height`, `depth`, where `width` is the contiguous dimension and `depth` the least contiguous dimension. I'll call this standard "Pixel-Major" since it's neither Row or Column Major and mentally maps to dealing with 3D graphics.

Annoyingly it's the same API one has to use when dealing with matrices and cubes, but at least it's clear that they are Pixel Major and the user can then decide whether they need to mentally transpose their dimension arguments before calling these methods.

**Preference**: keep CUDA argument names of `width`, `height` and `depth` for memory allocation. Acknowledge these are in "Pixel-Major" and are neither Row/Column-Major.

Another relevant API is cuBLAS where all calls are implicitly Column-Major, but the user can pass a `Transpose` / `NoTranspose` argument.

**Preference**: leave the burden of knowing and handling the fact that BLAS is Column-Major to the library user.

## Copy2D/3D from/to Host

When doing CUDA programming, clearly the library user cares about performance. Implicit O(n) operations that are not part of CUDA specification are a big no-no.

**Preference**: Providing explicit methods for doing transpose copy operations is okay, but they should not be the default or implicit. Make sure there is a real demand for these extra methods, I suspect most CUDA programmers are happy with simple Copy.

## Offsets and Strides

Representing vectors, matrices, and cubes using an `offset`, `stride0`, `stride1`, and `stride2` and (or `inc` or `pitch` or whatever you want to call them) is very powerful, and means that you can slice them (e.g. take a matrix view out of a cube view) in many surprising ways (e.g. `stride1 == 0` means a repeated-vector matrix).

This is a problem I've got some personal experience with, gained while developing a TensorFlow-like framework that deals with vectors, matrices, cubes and hypercubes. While the offset + strides is very powerful, the reality is we ended up sprinkling the code with constrained preconditions (i.e. `stride0 == 1` this input matrix must be dense in memory) and only implemented the code paths to support these fast representations (and throw exceptions when the input didn't match those expectations).

When doing CUDA programming, clearly the library user cares about performance. So I would avoid `ArrayViews` that makes the code slower either because ILGPU has to generate more instructions to account for offset and strides, or because it lulled the user into a false sense of security but made his memory accesses really inefficient in practice.

**Preference**: Limit slicing operations to only those that keep the `stride0 == 1` invariant and match the C# `k, j, i` memory locality guarantees described above. I expect this invariant will help keep the kernel as fast and efficient as they currently are. This specifically excludes the proposed "cheap" transpose (i.e. changing the strides, which is not cheap at all when you actually have to access non-contiguous elements in memory).

## Pitched allocation

I do want to have access to CUDA multi-dimensional allocation functions (`cudaMalloc3D` and `cudaMallocPitched`). IIRC you ask for memory for the given `width`, `height` and `depth` and CUDA ensures that the elements along the `width` dimension are contiguous in memory and aligned such that each vector along that dimension can be accessed with memory-coalescent access. It returns the pitch of the `weight` dimension (i.e. equivalent to `stride1` in my explanation above - with `stride2` being implicit).

**Comment by Ruberik** [comment]
Thanks to @GPSnoopy for breaking it down. I agree particularly with their preferences under "Offsets and Strides" and "Copy2D/3D from/to Host." I tentatively agree with the switching index order for multidimensional array access, but I don't know what a migration plan would look like. It would have to be a good one.

**Comment by Joey9801** [comment]
@GPSnoopy: That's a pretty comprehensive writeup to respond to, but I'll try to break down my opinions under the same headings:

## Multi-Dimensional Access using C#

I think the order of array indices is purely syntactic sugar, and doesn't necessarily have to have anything to do with the underlying order in memory.

The most logical constraint I can think of is one where if an array is copied between the host and accelerator, accessing the data with the same indicies in the same order references the same element on both the host and the accelerator, though this is perhaps more a contraint on the Copy API than it is anything else.

## Row Major, Column Major and "Pixel" Major CUDA APIs

I find this statement concerning:
> the user can then decide whether they need to mentally transpose their dimension arguments before calling these methods

This is effectively the same argument as the one for using a regular `float` to represent different units of measurement (eg meters, kilograms, euros, etc..). I'm sure that most developers reading this will have at least a handful of stories about code they've worked with, where the original author had to mentally remember which variables had which units and accidentally got it wrong - I certainly have.

Some programming languages have the ability to represent this sort of unit information for variables, eg F#'s "units of measure", or Haskells "Newtype". In these languages the compiler can warn the user if they are incorrectly mixing units (or indeed, prevent them from doing so outright), while incurring zero runtime cost over a plain float. There is a fantastic opportunity here to do a similar thing for ILGPU arrays, and I think it would be a tremendous shame if the idea was dismissed without being fully explored and discussed here.

## Copy2D/3D from/to Host

I think it is uncontroversial that the Copy operations should do a little rearranging of the data as possible during the copy.

There is some subtlety in these APIs for pitched allocations. Eg should a pitched accelerator array -> dense host array copy operation copy the contiguous dimension in chunks to avoid the alignment padding, or faithfully include the garbage values in the padding in the CPU array? (I think the former)

## Offsets and Strides

I strongly disagree with the idea that APIs which could result in non-performant views should just be excluded. There are certainly use cases for such views even in the context of hightly performant code. Not every array access is on the hot path.

Part of being a "library user that cares about performance" is being able to make informed tradeoffs when implementing a kernel. For example I might be implementing a kernel that does many expensive cuBlas operations that only accept column-major data, and find that it is faster to do a small non-cuBlas operation on a "cheaply transposed" view of the same data than it is to perform a full transposing copy of the data first.

Complex indexing logic is the sort of code that is very easy to get subtly wrong in practice without compiler assistance. I believe the added confidence that I could have in the correctness of non-trivial indexing code by using non-dense ArrayViews easily pays for the cost of including the occasional `debug_assert(arr.strideX == 1)` where it matters. It is not unimaginable that ILGPU could even make use of such debug assertions during optimisation passes at some point in the future.

> ..slower either because ILGPU has to generate more instructions to account for offset and strides...

@m4rs-mt's suggestion of leveraging ILGPUs specialization feature for eliding the extra stride value entirely is imo a very good way that a performance concious developer could guard their code against any unnecessary overhead. It's also worth benchmarking what this overhead actually is before using it to motivate a decision either way - my intuition is that in the context of a real kernel that does non-trivial work, the overhead would be insignificant.

**Comment by Aleksey1555** [comment]
Copy2D/3D from/to Host:
Simple: delete transformation from row-major order to column-major order (for 2D and 3D arrays)  and delay about 10sec (whitch i have) will disappear)))

**Comment by Joey9801** [comment]
[I have had a go at implementing the sort of API I was thinking of](https://github.com/Joey9801/ilgpu-arrayview-sketch/blob/master/Demo/Demo.cs) as a wrapper around a simple 1D `ILGPU.ArrayView`. It's a real API that does actually work inside ILGPU kernels.
The big feature is that it leverages dynamic specializations to (as far as I can tell from looking throught the generated PTX) completely elide the hypothesized overhead of working with stride variables that can be proven at compile time to be exactly 1. The custom ArrayView struct takes a "stride" generic type parameter, which is either "general" where the stride in any dimension may take any value, or "DenseX"/"DenseY"/etc.. which has a compile time constant value of `1` for one of the dimensions.

In [Allocator.cs](https://github.com/Joey9801/ilgpu-arrayview-sketch/blob/master/Allocator.cs) I had a go at writing methods that allocate row-major ("DenseX"), col-major ("DenseY"), and even a simple emulated pitched allocation example. Each of these methods just allocates a basic 1D `ILGPU.MemoryBuffer` and layers the same custom N-dimensional ArrayView struct on top of it with the appropriate stride generic type parameter.

I'm not claiming that the API sketched out above is exactly what ILGPU should adopt, but I hope that having it written down will give us all something concrete to key off and discuss.

**Comment by m4rs-mt** [comment]
@Joey9801 To my mind this has an overlap of about 95% of the abstract concept I had in mind based on your comments regarding runtime concerns/additional abstraction overhead🥇🎉 I think that your design ensures that the abstractions are automatically lowered into highly efficient code without worrying about potentially "hidden" compiler features 🚀
