### ISSUE TITLE
Correct kernel for Cuda accelerator

### ISSUE THREAD

**Issue by euroUK** [m4rs-mt/ILGPU#347]
Hi!

I am newbie in GPU calculation. I'm trying to calculate simple task that used in one of my algorithms. 
I have int[,] array with 32 column counts and up to several millions rows. Each row should be bitwise & with others to find if one is contained by another. I'm returning 1D array with extra rows to remove in main app part. 

The very basic attempt (somehow I can't  int[] res = new int[aView.Width];) looks like 
```cs
static void ArraySimplifierKernel(Index1 index, ArrayView2D<int> aView, ArrayView<byte> cView)
        {
            var x = index.X;
            var fElement = aView.GetRowView(x);
            int[] res = new int[64];
            for (var i = x+1; i < aView.Height; i++)
            {
                if (i != x)
                {
                    var cElement = aView.GetRowView(i);
                    for (int j = 0; j < fElement.Length; j++)
                    {
                        var idx = new Index1(j);
                        res[idx] = fElement[idx] & cElement[idx];
                    }
                    if (CompareBitArrays(fElement, res))
                    {
                        //felement is base for cElement
                        cView[new Index1(i)] = 1;
                    }
                    else if (CompareBitArrays(cElement, res))
                    {
                        cView[new Index1(x)] = 1;
                    }
                }
            }
        }
```

The main problem is that my CPU (Ryzen 5950x) calculation is about 10 times faster than CUDA (3090) while it looks like GPU is not loaded more than 5 percent. What am I doing wrong? Also is it possible to use bit array (I have error that bit is not bittable).

Thank you!

**Comment by MoFtZ** [comment]
@euroUK welcome =)

There are a few things to consider when doing GPU programming, some are specific to ILGPU, and some more general.

First, bit/bool is not blittable. This is a limitation of the .NET framework - the boolean type cannot be directly translated to an unmanaged type. If you want to have a compact representation, you can use `byte` and deal with bit flags yourself. You can find [more information here](https://docs.microsoft.com/en-us/dotnet/framework/interop/blittable-and-non-blittable-types).

Second, dynamic memory allocation on the GPU is not the same as on the CPU. It is not possible to perform ` int[] res = new int[aView.Width];` because the size of the array is not constant.

Third, using your hardware as an example, your CPU has 16 cores/32 threads, and your GPU has 10496 GPU/Cuda cores. A single CPU core is much faster than a single GPU core. You might need to re-write your algorithm to take advantage of many GPU cores.

Fourth, since you are using a 2D array, be aware that ILGPU will transpose the array from [Row-Major order to Column-Major order](https://en.wikipedia.org/wiki/Row-_and_column-major_order). This could also have an impact on performance.

Are you able to provide the source code to a small working example of your algorithm? I'm not entirely clear on what your algorithm is doing, particular with the `CompareBitArrays` function, and the expected output in `cView`.

**Comment by MoFtZ** [comment]
OK, I made a small sample program with your code, taking a guess at the implementation of `CompareBitArrays`.

I also made a change to the algorithm so that comparing bit arrays would terminate early. This appears to give a significant boost in performance. On by GTX 1070, 50k rows can be processed in around 1 second versus 12 seconds.

[Issue347.zip](https://github.com/m4rs-mt/ILGPU/files/5658777/Issue347.zip)

Based on your original performance, this only makes it as fast as your CPU implementation. It could also be that your algorithm is just better suited for running on the CPU.

**Comment by euroUK** [comment]
Thank you for provided optimization!

Now it's working faster. And based on my solution, I found the reason why my GPU code was so slow.
You used matrix height threads for GPU, while I used width. So on my 16/32 CPU  32/64 threads was ok, but for GPU it was too low.

> - Accelerated implementation on CPUAccelerator [WarpSize: 1, MaxNumThreadsPerGroup: 32, MemorySize: 9223372036854775807] with 16 threads: 453ms
> - Accelerated implementation on GeForce RTX 3090 [WarpSize: 32, MaxNumThreadsPerGroup: 1024, MemorySize: 25769803776] with 1600 threads: 437ms
> - Accelerated implementation on CPUAccelerator [WarpSize: 1, MaxNumThreadsPerGroup: 32, MemorySize: 9223372036854775807] with 24 threads: 201ms
> - Accelerated implementation on GeForce RTX 3090 [WarpSize: 32, MaxNumThreadsPerGroup: 1024, MemorySize: 25769803776] with 2400 threads: 264ms
> - Accelerated implementation on CPUAccelerator [WarpSize: 1, MaxNumThreadsPerGroup: 32, MemorySize: 9223372036854775807] with 32 threads: 67ms
> - Accelerated implementation on GeForce RTX 3090 [WarpSize: 32, MaxNumThreadsPerGroup: 1024, MemorySize: 25769803776] with 3200 threads: 244ms
> - Accelerated implementation on CPUAccelerator [WarpSize: 1, MaxNumThreadsPerGroup: 32, MemorySize: 9223372036854775807] with 40 threads: 68ms
> - Accelerated implementation on GeForce RTX 3090 [WarpSize: 32, MaxNumThreadsPerGroup: 1024, MemorySize: 25769803776] with 4000 threads: 243ms
> - Accelerated implementation on CPUAccelerator [WarpSize: 1, MaxNumThreadsPerGroup: 32, MemorySize: 9223372036854775807] with 48 threads: 70ms
> - Accelerated implementation on GeForce RTX 3090 [WarpSize: 32, MaxNumThreadsPerGroup: 1024, MemorySize: 25769803776] with 4800 threads: 242ms

On 64/100000 matrix

**Comment by euroUK** [comment]
Hi!

Thank you for optimizing my code!
Finally, I realized where I was wrong. As Index I provided column count, not row. That is why CPU is faster. When I fixed it GPU is  faster!
