### ISSUE TITLE
What happens if shared memory is allocated and used in an implicitly grouped kernel?

### ISSUE THREAD

**Issue by Costigan** [m4rs-mt/ILGPU#348]
In a now-closed issue (https://github.com/m4rs-mt/ILGPU/issues/51), I submitted sample code and asked how to interpret a runtime error message.  The problem turned out to be a small bug in ILGPU which was fixed, but @m4rs-mt recognized another error in my code in passing.  I allocated and used shared memory in a kernel that I was calling with implicit grouping.  Here's what you said at the time:

_Note that using shared memory in combination with implicitly grouped kernels can lead to undefined and unintended behavior. We should add an error message to ILGPU that simply forbids such kernels. Please use an explicitly grouped kernel to have fine-grained control regarding the number of threads per group._

I ended up solving my problem then in a completely different way, without using my GPU, and I totally missed this comment.  I'm now coming back to it after realizing I've made the same mistake in other code.

So here's my question: Is the behavior undefined?  Or does ILGPU behave in this situation as if I'd declared thread local memory, i.e., each thread gets a unique array allocated in global memory?  I'm asking because I have a large set of results that I've calculated using a kernel with this mistake in it.  The results would be correct if ILGPU behaved as if thread local memory had been allocated; the kernel would have just run more slowly.  If the results are truly undefined, then I have a larger problem.

I was using version 0.7.0 at the time and am still using that.   (I know.  I'll catch up soon. 8^)

I think an error message in this situation would be useful for beginners like me.  However, I don't even know where such an error message would be presented to me.  Would it be a runtime exception?  There's no explicit mention of how ILGPU-related compile-time errors are conveyed to users in http://www.ilgpu.net/Documentation

**Comment by MoFtZ** [comment]
In an implicitly grouped kernel, if you ask for Shared Memory, you will get Shared Memory, not thread local memory.

Shared Memory is allocated per group. and the memory is uninitialized.

The issue with using Shared Memory in an implicitly grouped kernel is that you have no control over the number of threads per group, nor the number of groups - these are selected automatically by ILGPU. The selection process is an implementation detail and should not be relied upon - it may change at any time.

Depending on how your algorithm uses the shared memory, you may be using uninitialized values, or even overwriting good values.

If you wish to use Shared Memory, please make sure to use explicitly grouped kernels.

Regarding error message, it will probably be a runtime exception when the kernel is compiled.

**Comment by Costigan** [comment]
@MoFtZ Thank you.  I had convinced myself that 0.7.0 behaved differently, but my test case was also incorrect.

What is the purpose of having implicitly grouped kernels with a manually-specified group size?  Isn't it the case that the user can only reduce performance by making a poor choice?  This isn't explained in http://ilgpu.net/Documentation#implicitlyGrouped nor is the example given particularly clear, because it only shows the kernel, not the launcher also.  The samples in ILGPU.Samples are very helpful and pretty well documented.  They do show an implicitly grouped kernel with a manually-specified group size but don't why one would choose to do that over other options.

Most of the examples in the dark column to the right of the documentation are clear and sufficiently detailed for new users to understand, but some aren't.  Perhaps there could be a section at the end of the documentation that suggests ways new users can find more information, one of which is to read the samples project.  Since it's a different project, someone who found ILGPU.net via a search engine may not know it exists for a while.

This question is probably more for @m4rs-mt .  I fall into a category of ILGPU user who is familiar with .NET and C# but not with Cuda or OpenCL.  Because of that, some things are unclear to me that would probably be clear to someone coming to ILGPU with Cuda or OpenCL experience.  One of those is the terminology.  A table of key terms used in the documentation listing Cuda and OpenCL equivalents would be helpful when referring to either Cuda or OpenGL documentation in order to learn the concepts.  Another is that more discussion of debugging and profiling is needed.  Using the CPU device and debugging with the .NET debugger is great.  But is it possible to use any of NVIDIA's tools for profiling or understanding memory behavior?  The documentation for those tools starts in such a different way that it's completely unclear whether they can be used.

**Comment by Ruberik** [comment]
@Costigan There can be more to it. Let's suppose you want a group to load some data, process it, and output the result. If the amount of data that you can process at once while fitting everything into shared memory requires a group size of 200 or less, then it makes sense to choose a group size of 200. I realize I'm not giving a very satisfying example, but there could be good performance reasons for wanting to take less than an automatically-assigned group size.

**Comment by Ruberik** [comment]
@MoFtZ, I see you've said:

> The issue with using Shared Memory in an implicitly grouped kernel is that you have no control over the number of threads per group, nor the number of groups - these are selected automatically by ILGPU. The selection process is an implementation detail and should not be relied upon - it may change at any time.

I'd like your help to understand the way this works, at a very high level. Let me throw out some assumptions, some of which are _certainly_ wrong, and let you tell me what I've messed up.

Let's suppose I'm passing an Index2 to my kernel that's `new Index2(50_000, 100)`. If I load my kernel with `LoadAutoGroupedStreamKernel(kernel)` on my Tesla T4 GPU, I'm guessing it's going to tackle elements `(0, 0) .. (1023, 0)` in the first group, elements `(1024, 0) .. (2047, 0)` in the second, and so on, until I guess the 48th group is `(49152, 0) .. (49999, 0)` (or maybe `(49152, 0) .. (175,1)`) and then the 49th is either `(0,1) .. (1023, 1)` or `(176, 1) .. (1199, 1)`.

I've been assuming that the same thing happens if I call `LoadImplicitlyGroupedStreamKernel(kernel, 1024)`, but it looks like that's wrong.

Can you give me some guidance about what's actually reasonable to assume about `LoadAutoGroupedStreamKernel`, and what I can do to say "Do the same thing, but with a smaller group size"? Because if that API doesn't exist, it would be extremely useful to have.

**Comment by MoFtZ** [comment]
@Ruberik When using explicitly grouped kernels, the developer has full visibility/knowledge of the internal algorithm, and also of the hardware device. They are aware of the memory requirements, so for example, the GPU has 8GB of RAM, and each warp in the algorithm requires 1GB, so they would not launch a group that is too large. They are aware of the compute requirements, so they may want to only use 10% of the GPU resources because another, more important, algorithm will also be running.

With the auto-grouped kernels, I believe the current goal of ILGPU is to achieve close to 100% occupancy of the GPU compute resources. It may also take into consideration the amount of dynamic shared memory, so if launching the kernel requires a lot of shared memory, it may limit the number of concurrent threads.



> Can you give me some guidance about what's actually reasonable to assume about `LoadAutoGroupedStreamKernel`, and what I can do to say "Do the same thing, but with a smaller group size"? Because if that API doesn't exist, it would be extremely useful to have.

There is currently no such functionality. You could probably access the [low-level Cuda APIs](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__OCCUPANCY.html#group__CUDA__OCCUPANCY) to retrieve rough estimates, and then supply your own values for explicitly grouped kernels.

**Comment by Ruberik** [comment]
Thanks for the explanation. I look at the KernelAccelerator version of [LoadAutoGroupedKernelInternal](https://github.com/m4rs-mt/ILGPU/blob/040f1c0b020b5a395b2cfbbf6a319883b6fa0b13/Src/ILGPU/Runtime/KernelAccelerator.cs#L94), which contains this code:

```
var result = CreateKernel(compiledKernel);
int groupSize = EstimateGroupSizeInternal(result, 0, 0, out int minGridSize);
result.Launcher = GenerateKernelLauncherMethod(compiledKernel, groupSize);
```

...and then I look at [LoadImplicitlyGroupedKernelInternal](https://github.com/m4rs-mt/ILGPU/blob/040f1c0b020b5a395b2cfbbf6a319883b6fa0b13/Src/ILGPU/Runtime/KernelAccelerator.cs#L62), which contains this code:

```
return CreateKernel(
    compiledKernel,
    GenerateKernelLauncherMethod(compiledKernel, customGroupSize));
```

Correct me if I'm wrong, but it looks to me like at least in the CUDA case, `LoadImplicitlyGroupedStreamKernel` is exactly the functionality that I asked for --- the same thing as `LoadAutoGroupedStreamKernel` but with custom group sizes -- isn't it? And whether I'm right or not, isn't that both straightforward and desirable functionality to have, regardless? As an experienced programmer but inexperienced GPU programmer, there's a huge difference to me between "This does the same magic, but with a different number from 1024" and "Here's full control," and it would be really nice to have access to the first of those two.

I understand that if I'm right, the only difference between what I want and what's there currently is that it isn't guaranteed to _stay_ that way, and so "using shared memory in combination with implicitly grouped kernels can lead to undefined and unintended behavior." I'd ask that we at least discuss making a version that _is_ guaranteed to be that way, whether it's as an optional parameter to `LoadAutoGroupedStreamKernel`, as `LoadImplicitlyGroupedStreamKernel`, or as something else.

**Comment by Ruberik** [comment]
Can we reopen this issue, or should we start a new one to discuss?

**Comment by MoFtZ** [comment]
@Ruberik You are correct in that you can provide a custom group size when loading an implicit kernel.

What is missing is an API to return the auto-calculated group size, which could then be manipulated. If you really want access to this number, you could try accessing the Cuda API directly.

However, if you are going to specify this custom group size, you could also use that same group size to load an explicitly grouped kernel.

My understanding of implicitly grouped kernels was to simplify the creation of algorithms, at the expense of more advanced functionality such as Shared Memory. Internally, it is just an explicitly grouped kernel with an initial step to compute the index.

You can replicate the same behaviour from within the explicitly grouped kernel by using a method like `Grid.ComputeGlobalIndex` to calculate the equivalent of the `Index1/2/3` parameter of an implicitly grouped kernel.

**Comment by Ruberik** [comment]
At this point I have to smack myself on the forehead and admit that I thought auto-grouped kernels were _allowed_ to use shared memory, and implicitly-grouped ones weren't. Obviously that wouldn't make any sense, so... yeah.

I guess I'm confused, because it looks like `LoadStreamKernel` just specifies a group size when you call the kernel, while `LoadAutoGroupedStreamKernel` and `LoadImplicitlyGroupedStreamKernel` determine it in advance. I can understand disallowing `LoadAutoGroupedStreamKernel` from using SharedMemory, because it's fairly safe to assume the caller hasn't done something reasonable to assume the groups are the size they've written their code for, but I'm still confused about why you'd want to disallow SharedMemory from `LoadImplicitlyGroupedStreamKernel`.

> What is missing is an API to return the auto-calculated group size, which could then be manipulated.

Isn't this covered by `LoadAutoGroupedStreamKernel(Action, out int groupSize, out int minGridSize)`?

Thanks for your patience.

**Comment by MoFtZ** [comment]
> Isn't this covered by `LoadAutoGroupedStreamKernel(Action, out int groupSize, out int minGridSize)`

I'll have to admit, I'm not familiar with that API - nice find.

> I'm still confused about why you'd want to disallow SharedMemory from `LoadImplicitlyGroupedStreamKernel`.

My guess is because the implicit grouping functionality is really just a thin wrapper on top of explicit grouping. Also, it was probably easier to just say "no shared memory" rather than try to define the expected behaviour, which may not suit everyone.

**Comment by Ruberik** [comment]
Fair enough -- I suppose I was making some major assumptions about how the groups would be put together. I put a migration guide in #354 for one dimension, in case other people are surprised by this change and want to know how to get their SharedMemory working again.

**Comment by m4rs-mt** [comment]
@Costigan @Ruberik Thank you very much for your feedback. I fully agree that we should reopen this topic or discuss it further in the project's associated `Discussions` forum. One of the reasons we don't support shared memory/advanced warp functions (such as shuffles) in any meaningful way at the moment is that implicitly grouped kernels perform multiple bounds checks "in the beginning" of the kernel function automatically. This allows the user to "forget" about explicit grouping and custom data padding/bounds checks that might be required depending on the group size. As mentioned above, these bounds checks are implicitly performed, resulting in threads "leaving" the kernel itself early. Hence, there is no guarantee that all threads of a group/warp reach a certain point in the kernel program... 🤔

**Comment by Ruberik** [comment]
@m4rs-mt There are two reasons I was opposed to switching to explicit kernels:

1. Code that I'd already written, which was working just fine, broke. Or was it working fine? And what percentage of people using that functionality had code that worked?
2. It seemed hard. It isn't, but I couldn't see a migration guide or examples. Can I suggest posting something like my example in #354 somewhere more official, and linking it from the error message? If I'd had that, my reaction would have been less "Why did they break something that works?" and more "Ugh, fine, I'll fix it."

Perhaps replacing the assertion with a warning in the next full version of the library, and with an Exception in the version after that, would give at least some people a chance to deal with migrating on their own schedule, rather than giving them something they have to fix right away.
