### ISSUE TITLE
Passing raw pointers around with Cuda acceleration

### ISSUE THREAD

**Issue by diwot** [m4rs-mt/ILGPU#360]
Hi,
I get wrong results using Cuda acceleration when using fixed size buffers:

		public unsafe struct float3
		{
			public fixed float XYZ[3];
		}

		public unsafe static void TestKernel(
			Index1 index, ArrayView<float3> S)
		{
			float3 s;
		
			s.XYZ[0] = 1;
			s.XYZ[1] = 2;
			s.XYZ[2] = 3;

			S[index] = s;
		}

	public RunTest()
        {
            gpu = new Gpu(true);

            var test = gpu.Accelerator.LoadAutoGroupedStreamKernel<
              Index1, ArrayView<float3>>(TestKernel);

            using (var s = gpu.Accelerator.AllocateExchangeBuffer<float3>(1024))
            {
                test(s.Length, s.View);
                gpu.Accelerator.Synchronize();

                s.CopyFromAccelerator();
                gpu.Accelerator.Synchronize();
            }
        }

After the last gpu.Accelerator.Synchronize(); all values in s.View are (1, 0, 3) but the kernel should actually write (1, 2, 3). It produces the correct result with the CPU accelerator.

**Comment by m4rs-mt** [comment]
@diwot Thank you for your issue report and welcome to the ILGPU community. I can confirm that I was able to reproduce your issue using the sample provided. It seems to be a frontend decoder issue that maps the address of the second element to a 4-element offset instead of a 4-byte offset. Surprisingly, this special case involving a single compile-time constant wasn't captured by our existing test cases.
