### ISSUE TITLE
Bounds checking is not done in debug mode

### ISSUE THREAD

**Issue by Ruberik** [m4rs-mt/ILGPU#371]
Perhaps my setup is wrong, but let's see:

http://www.ilgpu.net/Documentation#simpleKernels says: "Note that in Debug mode, every access to an ArrayView is bounds-checked." I don't believe that's currently true.

Here's my entire program. It initializes two MemoryBuffer<int> structures to 0, then executes a kernel to increment each element of the first MemoryBuffer. The kernel is deliberately asked to go past the end of the first buffer. There's no Exception, and the second MemoryBuffer's first element has been incremented. I'm running a Debug binary.

```
using System;
using ILGPU;
using ILGPU.Algorithms;
using ILGPU.Runtime;
using ILGPU.Runtime.Cuda;

namespace Test {
    public class Test {
        static void Main(string[] args) {
            using var context = new Context(ILGPU.IR.Transformations.OptimizationLevel.O0);
            context.EnableAlgorithms();
            using var accelerator = new CudaAccelerator(context);
            var kernel = accelerator.LoadAutoGroupedStreamKernel<Index1, ArrayView<int>>(TestKernel);
            using var arr = accelerator.Allocate<int>(1000);
            using var arr2 = accelerator.Allocate<int>(1000);
            accelerator.Initialize(accelerator.DefaultStream, arr, 0);
            accelerator.Initialize(accelerator.DefaultStream, arr2, 0);
            Console.WriteLine($"arr2[0] == {arr2.GetAsArray()[0]}");
            kernel(1050, arr);
            accelerator.Synchronize();
            Console.WriteLine($"arr2[0] == {arr2.GetAsArray()[0]}");
        }

        static void TestKernel(Index1 index, ArrayView<int> arr) {
            arr[index]++;
        }
    }
}
```

And here's my .csproj file, in case that's helpful:

```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netcoreapp3.1</TargetFramework>
		<ApplicationIcon />
		<OutputType>Exe</OutputType>
		<StartupObject />
		<RootNamespace>Test</RootNamespace>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="ILGPU" Version="0.10.0-beta1" />
	  <PackageReference Include="ILGPU.Algorithms" Version="0.9.2" />
	</ItemGroup>
</Project>
```

**Comment by m4rs-mt** [comment]
@Ruberik You are right 🤓 This issue was introduced in #196. This PR contained fundamental changes to the computation of view indexes. This feature was accidentally removed.

**Comment by Ruberik** [comment]
Question about the performance tradeoff: I would naively expect bounds checking to be about as fast as indexing itself. Any time you're indexing, I assume you're either reading or writing at least the L1 cache. What's the worst-case scenario for how much slowness the bounds checking adds? Depending on just how small that is, I might suggest leaving the bounds-checking in even under optimization.

**Comment by m4rs-mt** [comment]
> Question about the performance tradeoff: I would naively expect bounds checking to be about as fast as indexing itself

The check itself is quite cheap. However, the branches are typically really expensive in contrast to the actual checks. This is one of the reasons why we (at least currently) don't want to perform bounds checks in `Release` builds at runtime.

**Comment by Ruberik** [comment]
Thanks for the insight!

**Comment by m4rs-mt** [comment]
@Ruberik some additional extensions to my previous comments. On the one hand, it is about the performance of (predicated) branch instructions that might be negligible in many cases. Bounds check will cause several redundant instructions to be executed on the internal ALUs, that we definitely want to use for processing purposes on most cases 🚀.
On the other hand, it is also about register usage that often increases due to additional bounds checks. This becomes even more important in (nested) loop scenarios where register pressure can become an issue. Especially when there are many loop-bound dependencies that need to be remembered across multiple iterations. Therefore, bounds checks are not performed in all cases.

PR #375 adds supports for additional assertion checks at runtime that are automatically enabled for you, as soon as a debugger in attached to your applications (it is disabled otherwise). Moreover, you can also enforce those checks (even in release builds) by passing the flag `ContextFlags.EnableAssertions` to the `Context` constructor. This allows you to benefit from release-build optimizations while preserving all bounds checks at runtime.

**Comment by Ruberik** [comment]
All great information, especially `ContextFlags.EnableAssertions`. Thanks.
