### ISSUE TITLE
Feature request: add the ability to accurately measure kernel runtime

### ISSUE THREAD

**Issue by mikhail-khalizev** [m4rs-mt/ILGPU#399]
Cuda (as well as opencl) supports events that measure kernel runtime.
And it would be useful to add the ability to use them in ILGPU.

Cuda example:
```cuda
  // Allocate CUDA events that we'll use for timing
  cudaEvent_t start, stop;
  checkCudaErrors(cudaEventCreate(&start));
  checkCudaErrors(cudaEventCreate(&stop));

  // Record the start event
  checkCudaErrors(cudaEventRecord(start, stream));

  MatrixMulCUDA<32><<<grid, threads, 0, stream>>>(d_C, d_A, d_B, dimsA.x, dimsB.x);

  // Record the stop event
  checkCudaErrors(cudaEventRecord(stop, stream));

  // Wait for the stop event to complete
  checkCudaErrors(cudaEventSynchronize(stop));

  float msecTotal = 0.0f;
  checkCudaErrors(cudaEventElapsedTime(&msecTotal, start, stop));
```

**Comment by m4rs-mt** [comment]
@mikhail-khalizev Thank you for your feature request. I guess it makes sense to add something like this 🤓 . One question that comes to mind is whether it is not sufficient to measure the time between the start of the kernel (perhaps a previous synchronization point) and the end of a call to `cudaStreamSynchronize()`. This obviously leads to a coarse-grained approximation, but in practice gives more meaningful results in most cases, since the rest of the program usually has to wait for a GPU operation to complete anyway. I am not sure if this is sufficient in your case.

**Comment by mikhail-khalizev** [comment]
Yes, that's exactly what I'm doing now.
But my main goal is to measure time in order to optimize the kernel code.

Now I have to run profiling after compiling the kernel to understand whether the performance has improved or not. And for example, it was a surprise to me that copying an array from the kernel to global memory via int4 is faster than int2 and faster than int.

And this is very clearly seen when measuring the time through the profiler, but it is not very clear to see through measuring the CPU time - the spread of values ​​reached 10% (for a kernel with a runtime of about 100ms). And had to run it at least 10 times and average the time.
