### ISSUE TITLE
Kernel Exception with Version 0.10 beta1

### ISSUE THREAD

**Issue by geobimmodeling** [m4rs-mt/ILGPU#404]
Hi, 

I am getting kernel exception after upgrading to V0.10beta from V0.8.  Please see attached sample code, search "Issue" that indicate where problem comes from.

[V10Beta2Test1.zip](https://github.com/m4rs-mt/ILGPU/files/5906831/V10Beta2Test1.zip)

**Comment by Ruberik** [comment]
It isn't clear to me that's an ILGPU problem. Is it possible you updated other libraries at the same time?

I haven't worked with Vector2 before, but presumably Vector2.Zero is a constant, rather than a function that returns a zero-length Vector2. Mutating its members seems problematic. Try this outside of a kernel and see what happens.

**Comment by MoFtZ** [comment]
I am able to reproduce the issue on ILGPU v0.9.2, but not ILGPU v0.9.1.

https://github.com/m4rs-mt/ILGPU/blob/64ff328eee12b92c5b50894e8e355a874d55b3c4/Src/ILGPU/IR/Values/StructureValues.cs#L792-L794

The call to `Parent[Count]` is causing an index out of bound exception.

**Comment by MoFtZ** [comment]
Looks like this was introduced by https://github.com/m4rs-mt/ILGPU/pull/294.

A workaround is to use `ContextFlags.ConservativeInlining`.

**Comment by geobimmodeling** [comment]
ContextFlags.ConservativeInlining and [MethodImpl(MethodImplOptions.NoInlining)] work for me.  Does it have impact on perfermance?

**Comment by m4rs-mt** [comment]
@geobimmodeling Disabling aggressive inlining can slow down your program significantly. @MoFtZ Yes, you are right. The problem is caused by an invalid assertion check. We should change it to: `value.Type == Parent[access.Index]`
