### ISSUE TITLE
Bounds checking generates spurious failures in large views

### ISSUE THREAD

**Issue by Ruberik** [m4rs-mt/ILGPU#429]
I'm seeing a bounds checking failure under the following conditions:

* A very large MemoryBuffer (9,813,945,198 bytes in this case, but the specific size matters).
* Getting element (1<<31) - 68 of that MemoryBuffer, using an int index (I don't necessarily expect a predictable pattern to which numbers work and don't work).

This might seem pretty esoteric, but it came up for me in a scenario where I was batch-copying elements from one notionally two-dimensional MemoryBuffer to another, in batches of size slightly under 2^30. The first batch worked fine, but the second batch didn't.

This took a long time to track down, partly because the specific size of your very large MemoryBuffer matters. I get this failure if my MemoryBuffer is size `642*15,286,519 = 9,813,945,198`, but not if it's size `642*17,286,519 = 11,097,945,198` (bigger) or size `642*10,286,519 = 6,603,945,198` (smaller).

Note that the actual *memory access* seems to work fine if I turn off the assertion. Here's the code:

```
        static void Main(string[] args) {
            var contextFlags = Context.DefaultFlags | ContextFlags.EnableAssertions;
            //var contextFlags = Context.DefaultFlags;
            using var AcceleratorContext = new Context(contextFlags, ILGPU.IR.Transformations.OptimizationLevel.O2);
            AcceleratorContext.EnableAlgorithms();
            var Accelerator = new CudaAccelerator(AcceleratorContext);
            var putKernel = Accelerator.LoadStreamKernel<int, int, long, ArrayView2D<byte>>(PutKernel);
            var getKernelNoSubView = Accelerator.LoadStreamKernel<int, int, long, ArrayView<byte>, ArrayView<byte>>(GetKernelNoSubView);

            int subviewYSize = 1672495;
            int subviewXSize = 642;
            int yOffset = 1672495;
            int itemCount = 15286519;

            Console.WriteLine(((subviewYSize + (int)yOffset) - 1) * subviewXSize + subviewXSize - 1);  // int index of the item to set/get
            Console.WriteLine(itemCount);
            using var arr = Accelerator.Allocate<byte>(subviewXSize, itemCount);
            arr.MemSetToZero();
            using var output = Accelerator.Allocate<byte>(1);
            Accelerator.Synchronize();
            putKernel(new KernelConfig(1, 1, SharedMemoryConfig.Empty), subviewYSize, subviewXSize, yOffset, arr);
            Accelerator.Synchronize();
            getKernelNoSubView(new KernelConfig(1, 1, SharedMemoryConfig.Empty), subviewYSize, subviewXSize, yOffset, arr.AsLinearView(), output);
            Accelerator.Synchronize();
            var result = output.GetAsArray();
            Console.WriteLine(result[0]);
            Accelerator.Dispose();
        }

        public static void PutKernel(
            int subviewYSize,
            int subviewXSize,
            long yOffset,
            ArrayView2D<byte> destination) {
            destination[subviewXSize - 1, yOffset + subviewYSize - 1] = 5;
        }

        public static void GetKernelNoSubView(
            int subviewYSize,
            int subviewXSize,
            long yOffset,
            ArrayView<byte> source,
            ArrayView<byte> destination) {

            destination[0] = source[((subviewYSize + (int)yOffset) - 1) * subviewXSize + subviewXSize - 1];
        }
```

Here's the output:

```
2147483579
Kernel:0: block: [0,0,0], thread: [0,0,0] Assertion `Index out of range` failed.
Unhandled exception. ILGPU.Runtime.Cuda.CudaException: device-side assert triggered
   at ILGPU.Runtime.Cuda.CudaAccelerator.SynchronizeInternal()
   at ILGPU.Runtime.Accelerator.Synchronize()
   at <>.Misc.Main(String[] args) in C:\Gotham\main\FurrowUtilities\Misc\Misc.cs:line 75
```

And here's the output if I turn off the assertion:

```
2147483579
5
```

**Comment by MoFtZ** [comment]
It looks like the `GetKernelNoSubView` kernel is triggering the assertion at line 262:
https://github.com/m4rs-mt/ILGPU/blob/658ae3dc729bd4d76fc837e0817d5394c7e45350/Src/ILGPU/ArrayView.cs#L256-L266

The code is accessing a large `ArrayView` (with `Length` greater than `int.MaxValue`), and using `int` as the indexer data type.

There is an alternate indexer for `ArrayView` that accepts `long` as the indexer data type. If you use this alternate indexer, the assertion will not occur.

**Comment by Ruberik** [comment]
That's a really useful assertion for large `ArrayView`s! A few concerns, though:

* I don't think that's the assertion that's triggering. If it is, it isn't triggering consistently. It doesn't trigger if `itemCount = 17286519`, for example, which makes the `ArrayView` even larger (there's another example in my initial post).
* Can I suggest changing the error message to reflect that it's the `ArrayView`'s size, not the index, that's out of bounds? I suppose `Index out of range` could refer to either, but "`ArrayView` size" isn't where my mind went.
* It looks like I oversimplified my repro, because the same error message appears when the `ArrayView` is of size under `int.MaxValue`. Replace the kernel in the repro above with this, and you still see the crash:
```
        public static void GetKernel(
            int subviewYSize,
            int subviewXSize,
            long yOffset,
            ArrayView<byte> source,
            ArrayView<byte> destination) {

            var source2D = source.GetSubView(yOffset * subviewXSize).As2DView(subviewXSize, subviewYSize);
            destination[0] = source2D[subviewXSize - 1, subviewYSize - 1];
        }
```

Here, `source2D` is an `ArrayView2D<byte>` of size `1,073,741,790`, but setting its last element fails an assertion. I'll note that the element of `source` this accesses is the same element as `GetKernelNoSubView` accessed. This has the same feature that whether it fails an assertion or not depends on the exact size of the underlying `MemoryBuffer`.

**Comment by MoFtZ** [comment]
In your second example `GetKernel`, `source2D` being accessed using the indexer that accepts two `int` parameters. This then creates an `Index2` and calls the `ArrayView` indexer that acccepts an `Index2` parameter.
https://github.com/m4rs-mt/ILGPU/blob/658ae3dc729bd4d76fc837e0817d5394c7e45350/Src/ILGPU/ArrayViewExtensions.cs#L313-L323

The implementation of this indexer that accepts `Index2` as a parameter is defined in a T4 template:
https://github.com/m4rs-mt/ILGPU/blob/658ae3dc729bd4d76fc837e0817d5394c7e45350/Src/ILGPU/ArrayViews.tt#L124-L129

Notice the call to `ToIntView()`. This treats the `ArrayView` as a 32-bit memory buffer, and the `Length` argument will generate an assertion because the length is larger than `int.MaxValue`.

DISCUSSION:
The call to `ToIntView` may not be necessary? Or is this behaviour expected?

ISSUE: It looks like this assertion is never triggered in the `CPUAccelerator` - the `CudaAccelerator` injects assertions into the kernel, which are slightly different to the code used by the `CPUAccelerator`.

WORKAROUND:
If you call `source2D` using the indexer that accepts two `long` parameters, the assertion does not occur.

**Comment by MoFtZ** [comment]
TEST NOTES:
My Cuda accelerator has less memory, so I reduced `itemCount` to 9286519 in order to reproduce the issues.
```CSharp
int itemCount = 9286519; // 15286519
```

**Comment by Ruberik** [comment]
I suspect you're correct about this in the main, but I think it isn't that simple, because:
1. Not all sizes above `int.MaxValue` fail this assertion. My guess is that it toggles back and forth every `2^31` or so, but I have no real evidence of this.
2. The `ArrayView` on which `ToIntView()` is being called isn't of size above `int.MaxValue`. Perhaps the underlying `ArrayView` that is having `ToIntView()` called on it somehow?

Thanks for the workaround -- already in use! 👍

**Comment by MoFtZ** [comment]
Yes, you are correct that there is a truncation occurring.

When the `CudaAccelerator` injects the assertions into the kernel, it checks whether the `ArrayView` is being treated as a 32-bit or 64-bit memory buffer. If the `ArrayView` is being treated as a 32-bit memory buffer, but it is actually a 64-bit memory buffer, asking for the `Length` of the `ArrayView` will return the bottom 32 bits of the 64-bit length. This truncated value is then compared against `int.MaxValue`, which is why the assertion failures are not always triggered (depending on the size of the view).

This will need to be fixed.
