### ISSUE TITLE
Cannot use BigInteger !

### ISSUE THREAD

**Issue by AbedKarmi** [m4rs-mt/ILGPU#444]
How can we use BigInteger variable? I have tried all possible was, but did work. It gives error like :
Not supported compare or arithmetic value of type 'None'

**Comment by MoFtZ** [comment]
@AbedKarmi
Unfortunately,`BigInteger` is not supported because of the way its internals work. It is designed for arbitrarily sized numbers, so it manages an internal array, and performs frequent memory allocations and deallocations.

ILGPU requires that the values passed to the GPU follow the C# `unmanaged` constraint, which `BigInteger` does not.

Do you require the full numeric range? or do you just need slightly larger like 128-bit integers?

**Comment by AbedKarmi** [comment]
I want to do RSA, DSA calculations.

**Comment by MoFtZ** [comment]
I am not familiar with RSA, DSA calculations, so I cannot advise you on the numeric range that you will require.

You will need to decide on an upper/lower limit for your numbers. e.g. UInt128 or UInt256. Then, you can create your own structure to represent these numbers. e.g. UInt128 could be a structure with 4 UInt32s.

You may be able to find existing .NET implementations e.g. https://github.com/ricksladkey/dirichlet-numerics, although I have not personally tried this library with ILGPU. Note that these implementations must be .NET code only, rather than wrappers over C++ e.g. https://github.com/cpsusie/Int128.

If you are really asking for the equivalent of UInt4096, then you will need to create your own structure. You maybe be able to borrow some of the code from `BigInteger`, but make sure not to use reference types.

**Comment by m4rs-mt** [comment]
Alternatively, you might be able to use "big integers" in the scope of shared memory/local memory if you really have to dynamically adjust the bit width of your types.

**Comment by m4rs-mt** [comment]
I am closing this issue for now due to inactivity.
