### ISSUE TITLE
Compiler error running on GPU, works on CPU

### ISSUE THREAD

**Issue by bnemetchek2** [m4rs-mt/ILGPU#461]
"An internal compiler error has been detected" is all the error I get running the attached app.  It runs fine when using CPUAccelerator but fails using CudaAccelerator.  Any help or suggestions would be appreciated.

Thx!

[ILGPUtest.zip](https://github.com/m4rs-mt/ILGPU/files/6305533/ILGPUtest.zip)

**Comment by MoFtZ** [comment]
@bnemetchek2
It looks like the issue is with your structures. e.g.
```CSharp
public struct TestStruct3
{
    public TestStruct4[] items;
    public TestStruct3(bool dummy)
    {
        items = new TestStruct4[1];
    }
}
```

In particular, the `items` member is not allowed because ILGPU does not currently support reference types.
There is support for [fixed size buffers](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/unsafe-code#fixed-size-buffers), but that only applies to primitive types.

Also, I noticed that you are mixing ILGPU v0.10.1 and ILGPU.Algorithms v0.9.2. These two versions are not compatible. I would suggest either using ILGPU.Algorithms v0.10.0-beta1, or downgrading to ILGPU v0.9.2.

On a side note, I'm a bit disappointed that the generated error was not helpful - we've spent some time trying to make the errors more meaningful. Will look into improving the error handling around this issue.

If you require any other assistance, please let us know.

**Comment by bnemetchek2** [comment]
Thanks for the info.  It's weird that it works with the CPU version but not the GPU but, having created a few CUDA kernels in the past I know it's an entirely different beast.  I would like to say that I think this is an awesome project and look forward to any future enhancements to it.  Even the CPU version is working much faster than the native .NET code, likely because of the refactoring it requires but still pretty cool.
