### ISSUE TITLE
Does ILGPU support for .net5?

### ISSUE THREAD

**Issue by vietthanhcit** [m4rs-mt/ILGPU#500]
Does ILGPU support .net5?

I tried to test and compare performance between CPU and GPU on .NET Framework 4.6.1 and .net5

I see that on the .NET Framework 4.6.1, GPU faster than CPU about 50%.
However, on the .net5, CPU faster than GPU 

I use Stopwatch to test time.

I wonder if ILGPU support .net5? 
I see on your website mention that ILGPU support .net5

Here is devices info
![image](https://user-images.githubusercontent.com/37809928/121342367-c0d75600-c94b-11eb-923e-787e948b7e1b.png)

**Comment by vietthanhcit** [comment]
I attached 2 projects. For 4.6.1, please use project ImageProcessor

https://www.dropbox.com/s/k72qph651maool4/dotnet5GpuTesting.zip?dl=0#
https://www.dropbox.com/s/ar1sf4k7w91h31h/framework4.6.1GpGpuViaCs-2018.zip?dl=0

**Comment by MoFtZ** [comment]
hi @vietthanhcit, yes, ILGPU currently supports `net5.0` by providing a `netstandard2.1` implemention. In the future, we may provide a native `net5.0` implemention.

There is no known performance difference between the different implementations of ILGPU.

As for why one implementation is slower, looking at your sample code, your timings include the memory allocation, memory copies to/from the GPU, as well as large .NET array allocations. In addition, the .NET 4.6 example runs an identical test on Alea before running ILGPU. There could be any number of reasons to explain the performance difference because each of those actions can vary the results.

**Comment by vietthanhcit** [comment]
Thank you for your answer. However, I don't get your point. 
For .NET 4.6,  I tried many times and see that GPU is always faster than CPU.
![image](https://user-images.githubusercontent.com/37809928/121365465-e0c64400-c962-11eb-8dff-6547cd210c11.png)

However, for .net5, sometimes GPU faster than CPU, please see the image below.
![image](https://user-images.githubusercontent.com/37809928/121365724-18cd8700-c963-11eb-9437-eedadac798e8.png)

But sometimes CPU faster than GPU. 
![image](https://user-images.githubusercontent.com/37809928/121366002-516d6080-c963-11eb-93bc-a565ee34bf25.png)

I think GPU is always faster than CPU and very fast. Could you please tell me why?
And could you please give me an example of a Comparison between CPU (not CPUAccelerator) and GPU?

**Comment by MoFtZ** [comment]
> Thank you for your answer. However, I still haven't understood why .NET 4.6 works but .net5 doesn't work.

Here is a summary of the result timings you provided:
```
net46   TPL    1.42 seconds
net5.0  TPL    1.27 seconds
net5.0  TPL    0.82 seconds

net46   ILGPU  0.91 seconds
net5.0  ILGPU  0.89 seconds
net5.0  ILGPU  0.87 seconds
```
You will notice that the timings for ILGPU are fairly consistent between `net46` and `net5.0`. The key difference is that TPL in `net5.0` can be much faster than `net46`.

> I think GPU is always faster than CPU and very fast. Could you please tell me why?

This is not necessarily true. Each GPU "core" is actually slower than a CPU core. The advantage of GPUs are that they have many many more cores than a CPU.

There is also additional overhead when using the GPU, such as copying data to GPU memory, and back again. Notice that the timings for ILGPU includes copying memory to the GPU and back. For TPL, there is no such overhead because the memory is already in RAM. You will find that the data transfer probably takes up a large share of the time, in your sample code.

> And could you please give me an example (use .net5) of a Comparison between CPU (not CPUAccelerator) and GPU with big data, using GPU parallelism?

You might find this blog post by a community member to be helpful:
https://timiskhakov.github.io/posts/computing-the-convex-hull-on-gpu


To improve the performance of the GPU code, you should learn more about the GPU architecture, and how it is different to the CPU. There are many resources available from Nvidia, such as:
- [Technical Resources - Accelerated Computing](https://www.nvidia.com/en-us/training/resources/?activetab=custom-text-tab-group-1-2)
- [Cuda Programming Guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html)
    - [Performance Guidelines](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#performance-guidelines)
- [Cuda Best Practices Guide](https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html)

**Comment by vietthanhcit** [comment]
Hi @MoFtZ,

I have one more question, it's not in the scope of this previous question, but I hope you can answer it here.
Can we use multiple Nvidia cards to speed up performance? If yes, can ILGPU support doing that and you can give me an example code?

Best regards.

**Comment by MoFtZ** [comment]
Yes, you can use multiple GPUs, but they are independent of each other. That means you will need to partition the work yourself, or write your algorithm so that the GPUs can cooperate with each other.

Have a look here:
https://github.com/m4rs-mt/ILGPU/issues/397#issuecomment-778529864

**Comment by MoFtZ** [comment]
FYI, we also have an active community on Discord and a new Reddit group.
Discord : https://discord.com/invite/X6RBCff
Reddit : https://www.reddit.com/r/ILGPU/

**Comment by m4rs-mt** [comment]
I am closing this issue for now 🤓
