### ISSUE TITLE
ILGPU crashes on creating Context

### ISSUE THREAD

**Issue by sigland** [m4rs-mt/ILGPU#503]
I have NVIDIA RTX2060 and Intel UHD 630 in my laptop. ILGPU crashes at this simple code:
var context = new ILGPU.Context();

An unhandled exception of type 'System.AccessViolationException' occurred in ILGPU.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

I investigated a little. ILGPU crashes because of Intel UHD 630 driver 27.20.100.9466 (with opencl 3.0.x) at enumeration opencl devices step. With legacy driver 27.20.100.8691, ILGPU working just fine, but the latest Windows 10 don't.

I don't even need openCL but there is one and this is a dead end. I can't using legacy driver because the latest Windows 10 constantly crashes on it and  I'm unable to disable openCL devices in ILGPU through any option at all.

Temporary workaround is replacing c:\Windows\System32\OpenCL.dll (opencl 3.0.x supposedly) with legacy opencl.dll
v.1.2.11.0

**Comment by MoFtZ** [comment]
hi @sigland, thanks for reporting this issue, and taking the time to investigate further.

You could try using ILGPU v1.0-beta1, which has a change to the startup sequence so that initialising OpenCL can be disabled. The release notes are [here](https://github.com/m4rs-mt/ILGPU/releases/tag/v1.0-beta1). Please be aware there there are a number breaking changes to the API, and ILGPU.Algorithms and ILGPU.Samples have not yet been updated to support this version.

**Comment by sigland** [comment]
> You could try using ILGPU v1.0-beta1

It works! Thanks!
