### ISSUE TITLE
Shared memory and As2DView/As3DView usage

### ISSUE THREAD

**Issue by CsabaStupak** [m4rs-mt/ILGPU#558]
I'm a bit confused how to use the stride stuff with `As2DView`/`As3DView`. In my kernel I would like to work with 2D and sometimes with 3D version of dynamically allocated shared memory. Since there are no documentation on this topic yet I would like to know which stride setting is the fastest (and correct). Note I do not need to transform the 1D shared memory view - it is random anyway, I just need a 2D/3D view of that memory block. I guess that using the `As2D/3DView` call is fast - if it has a considerable performance hit, then I will rather avoid to use them and will use the ugly `nY * nDimX + nX` like approach (in that case this is a feature request :-) )...

Here I have a dynamic shared memory divided into two logical parts. The 2nd part - `cache2d`, is a 2D array. My understanding is that the `Stride2D.DenseY` is the fastest - not sure if here it is true or is there a simpler/faster approach to obtain a 2D view. According to `DenseY `c-tor I have to enter `xStride `value.

```
var shared = (ArrayView1D<float, Stride1D.Dense>)SharedMemory.GetDynamic<float>();
...
var cache2d = shared
    .SubView(16, 32)
    .As2DView((8, 4), new Stride2D.DenseY(8));
```

For 3D I don't know how to use. I would like to obtain a 3D array of size `[4, 2, 8]`. Here according to `Stride3D.DenseZY` c-tor I should enter `xStride `and `yStride `- in my case `[4, 2]` however by this the returned `cache3d `has less size. By trial-error approach I found that I have to enter `[4 * 8, 8]`. Could you explain why?

```
var shared = (ArrayView1D<float, Stride1D.Dense>)SharedMemory.GetDynamic<float>();
ref float fCacheVal = ref shared.SubView(0, 1)[0];

var cache3d = shared
    .SubView(1, 4 * 2 * 8)
    .As3DView((4, 2, 8), new Stride3D.DenseZY(4 * 8, 8));
```

Thanks :-)

**Comment by MoFtZ** [comment]
`As2D/3DView` does not physically transform the block of memory. It is still the same contiguous block of memory, just interpreted differently - when you access the view, it will perform the `nY * nDimX + nX`-style calculations on your behalf.

Regarding `Stride3D.DenseZY`, the constructor takes `xStride` and `yStride`. The stride refers to the number of elements to skip to get to the `X + 1` or `Y + 1`.

For example, to get to `Z + 1` you add 1 because that is the "most dense" dimension. The "next dense" dimension is `Y`, so to get to `Y + 1`, you add 8 to to skip over the `Z` values. Finally, to get to `X + 1`, you need to skip all the `Z` values *and* all the `Y` values (so `xStride` becomes `2 * 8`)

Remember that your buffer is a contiguous block of memory.
```
xStride |-------------------------------------------------|
yStride |----------------------|
zStride |-|
        X0                                                 X1
        Y0                      Y1                         Y0                      Y1
        Z0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z8 Z0 Z1 Z2 Z3 Z4 Z5 Z6 Z7 Z0 Z1 Z2 Z3 Z4 Z5 Z6 Z7
```

**Comment by CsabaStupak** [comment]
Now it is clear :-) Thanks!

**Comment by m4rs-mt** [comment]
@CsabaStupak An additional remark: `Stride2D.DenseY` is not "faster" than `Stride2D.DenseX` in general. I was just referring to the fact that `Stride2D.DenseY` means that the same memory layout is used as in .Net, which improves the transfer speed between CPU and GPU. Otherwise, it just depends on your access patterns within your kernel 😄.

**Comment by m4rs-mt** [comment]
@CsabaStupak @MoFtZ Maybe we should provide additional overloads to simplify using the `AsNDView` methods? I was thinking about something like `someView.AsNDDenseYView(extent)`, which automatically "infers" the "right" `DenseY` stride information.

**Comment by CsabaStupak** [comment]
That is a good idea. It follows the Accelerator.Allocate2DDenseY like methods :-)

**Comment by MoFtZ** [comment]
Sounds like a useful addition 👍
