### ISSUE TITLE
[Feature request] Execute native PTX code

### ISSUE THREAD

**Issue by mikhail-khalizev** [m4rs-mt/ILGPU#587]
At the moment, the following technology is obtained: C# is compiled to IL, and then from IL is converted to PTX and run on a video card.

On the one hand, this is good and convenient - you can run some of the C# methods on the GPU. Unfortunately, the quality of the code sometimes suffers. And I noted a rather non-optimal PTX code, simply because at the C# -> IL stage, the quality drops a lot for the GPU.

Therefore, an idea appears, especially demanding parts to be written manually on PTX and then built into C#. And so my suggestion is to add user-friendly functions so that you can create a Kernel from PTX code (specified as a string). And run in the same way as other kernels.

**Comment by MoFtZ** [comment]
In ILGPU v1.0.0-beta1, the `CudaAsm` class was added to support inline PTX assembly.

The original PR is https://github.com/m4rs-mt/ILGPU/pull/467.

The inline PTX assembly documentation can be found here:
https://docs.nvidia.com/cuda/inline-ptx-assembly/index.html

`CudaAsm.Emit` attempts to mimic `asm`, so it uses `%0` and `%1` rather than the .NET convention of `{0}` and `{1}` for placeholders. It is also important to terminate the PTX instruction with `;`.

Also, `asm` allows the user to specify the register type. However, `CudaAsm` uses the input variable type to determine the register type.

Here is an example program:
```CSharp
public class Program
{
    public struct UInt128
    {
        public readonly ulong High;
        public readonly ulong Low;

        public UInt128(ulong high, ulong low)
        {
            High = high;
            Low = low;
        }

        public override string ToString()
        {
            var bi = new BigInteger(High);
            bi <<= 64;
            bi += Low;
            return bi.ToString();
        }
    }

    public static void MyKernel(Index1D index, ArrayView<UInt128> buffer)
    {
        // NB: Need to convert index.X to ulong, so that %2 will use the correct PTX register type.
        ulong multiplier = (ulong)index.X;
        CudaAsm.Emit("mul.hi.u64 %0, %1, %2;", out ulong high, ulong.MaxValue, multiplier);
        CudaAsm.Emit("mul.lo.u64 %0, %1, %2;", out ulong low, ulong.MaxValue, multiplier);
        buffer[index] = new UInt128(high, low);
    }

    static void Main()
    {
        using var context = Context.CreateDefault();
        using var accelerator = context.CreateCudaAccelerator(0);
        using var buffer = accelerator.Allocate1D<UInt128>(1024);

        var kernel = accelerator.LoadAutoGroupedStreamKernel<Index1D, ArrayView<UInt128>>(MyKernel);
        kernel((int)buffer.Length, buffer.View);

        var results = buffer.GetAsArray1D();
        for (var i = 0; i < results.Length; i++)
            Console.WriteLine($"[{i}] = {results[i]}");
    }
}
```

Something that did occur to me is that `CudaAsm` will build a string that is inlined into the final PTX. That makes it possible to perform a "PTX injection" attack.. 😆

**Comment by mikhail-khalizev** [comment]
Thanks a lot.
