### ISSUE TITLE
What is allowed or not in kernels?

### ISSUE THREAD

**Issue by weierstrass1** [m4rs-mt/ILGPU#63]
I have a question, when you do a kernel, what is allowed?

for example can kernel:
- call functions of static classes? 
- use Convert._(param) (for example Convert.Int32(foo))
- use custom classes or structs?
- use local parameters if it is called into a method?
- use class variables if it is called into a class?
etc...

**Comment by m4rs-mt** [comment]
@weierstrass1 Kernels can call other static functions and "instantiate" other (user-defined) structure types. Reference types (such as strings) are not supported, since they generally require heap-based memory management. There will be limited support for class types in the future. A selection of different functions and examples can be found in the [samples repository](https://github.com/m4rs-mt/ILGPU.Samples).
