### ISSUE TITLE
Review of ILGPU v0.4.0-beta

### ISSUE THREAD

**Issue by samy2** [m4rs-mt/ILGPU#8]
Hi,
I tried to migrate an application from ILGPU 0.3 to ILGPU 0.4.0-beta.
The migration process was quite easy.
I find the new API user friendly :
	- The explicit use of Cuda Streams will make the development of multi-threaded applications easier
	- The new way of declaring shared memory is easy to work with
What I personally don't like in the API is not new : it is the poor naming of the GroupedIndex struct members, that makes writing and reading kernels difficult for Cuda developers.

For example : this is a typical AleaGPU kernel, that every Cuda programmer can understand :

```
private static void Kernel(int[] result, int[] arg1, int[] arg2)
{
    var start = blockIdx.x * blockDim.x + threadIdx.x;
    var stride = gridDim.x * blockDim.x;
    for (var i = start; i < result.Length; i += stride)
    {
        result[i] = arg1[i] + arg2[i];
    }
}
```

Here is the equivalent in ILGPU 0.3 or 0.4beta :

```
private static void Kernel(GroupedIndex index, ArrayView<int> result, ArrayView<int> arg1, ArrayView<int> arg2)
{
	var threadIdx = index.GroupIdx;
	var blockIdx = index.GridIdx;
	var blockDim = ILGPU.Group.Dimension.X;
	var start = blockIdx * blockDim + threadIdx;
	var stride = Grid.Dimension.X * blockDim;

	for (var i = start; i < result.Length; i += stride)
	{
		result[i] = arg1[i] + arg2[i];
	}
}
```

Why the hell is the thread index called "GroupIdx", and the block index "GridIdx" ?

After migrating to ILGPU 0.4beta, I wasn't able to make the application working, because several kernels cannot compile any more. Here is an example of a simple kernel that doesn't work any more (ILGPU.Runtime.Cuda.CudaException : 'a PTX JIT compilation failed') :

```
[Test]
public void CompilationTest()
{
	using (var context = new Context())
	{
		using (var gpu = new CudaAccelerator(context, 0))
		{
			var kernel = gpu.LoadKernel<GroupedIndex, ArrayView<float>, float>(MyFirstKernel);
		}
	}
}

private static void MyFirstKernel(GroupedIndex index, ArrayView<float> array, float value)
{
	array[index.ComputeGlobalIndex()] =  value / 2;
}
```
Anyway, thank you for the hard work - ILGPU is a very good CUDA framework!

**Comment by kant2002** [comment]
I would list following issues which I have to walk though during moving samples to 0.4.0-beta

## ILGPU changes

1. `Atomic.Sub` missing. Not sure, but I believe that I should replace with `Atomic.Add(… , -value)` 
2. `dataView.GetVariableView(3)` replaced with `ref dataView.GetVariableView(3).Value`
3. `buffer.GetAsArray()` replaced with `buffer.GetAsArray(accelerator.DefaultStream)`
4. `accelerator.LoadAutoGroupedStreamKernel` should be replaced with `accelerator.LoadAutoGroupedKernel` and then pass `accelerator.DefaultStream` as additional first argument to created kernel.
5. `CompileUnitFlags` looks like replaced with `IRContextFlags` and these parameters now should be passed during creation of the `Context`, and not during call to `Accelerator.Create`
6. `GPUMath`  replaced with `XMath`
7. `variableView.Store(value)` replaced with `variableView.Value = value`
8. `buffer.CopyFrom` now require passing additional parameter `accelerator.DefaultStream`
9. `Warp.Reduce` removed, and no alternative given as far, I aware. WarpShuffle sample I could not port.
10. `Accelerator.LoadSharedMemoryStreamKernel1` not available, or I do not find proper replacement
11. `SharedMemory` seems to be not available too

## ILGPU.Lighting changes
ILGPU.Lightning for 0.4.0-beta not available yet

After some testing, I think I may migrate not all applications correctly, so I will play with migration more.

**Comment by m4rs-mt** [comment]
First of all: thank you very much for your feedback 👍 👍 

@samy2 Regarding your compilation issues:
The generated PTX instructions are
```
	mul.wide.u32	%rd3, %r4, 4;
	add.u64	%rd2, %rd1, %rd3;
	mov.f32	%f2, 0f40000000;
	div.f32	%f3, %f1, %f2;
	st.f32	[%rd2], %f3;
```
However, in case the 'div' instruction should include a rounding or an approximation modifier (workaround: use RCP).
Furthermore, there are additional issues when compiling intrinsic math functions working on floats and/or doubles.
These issues will be fixed in the next version.

@samy2 Can you provide additional minified samples of your kernels that fail to compile at the moment?

@kant2002 I will publish an updated Lightning library on Sunday on GitHub. This version includes a new Warp.Reduce implementation.

1. Yes, you are right.
2. Yes. I added additional support for the 'new' C# 'ref' features. VariableView is still available and can be seen as pointer to variable (a 'ref' variable) that can be stored in the scope of structures.
3. Yes; I have removed implicit stream handling in favor of explicit streams to avoid synchronization problems that can occur during programming.
4. See 3. However, I will re-add additional implicit stream handlers in the next version (this feature was requested by many users).
5. Yes; the concept of a single CompileUnit does not make much sense in the new compiler
6. Many people requested a renaming of the old GPUMath class in order to express a 'cross platform' math helper that also works on the CPU. The name "XMath" was a community request. I am also working on a new fast-math library that will replace the XMath class (Q1/Q2 2019).
7. Yes
8. Yes
9. Warp.Reduce is a higher-level function(compare to other low-level functionality of the ILGPU library) that realizes a specific reduce algorithm. Therefore, it was move to the new ILGPU.Lightning library.
10. No longer needed. These attributes have been removed in favor of a static allocation manager that is more intuitive and offers more flexibility than kernel parameters. See #6 for more information.

**Comment by samy2** [comment]
Hi,
After more investigations : most of my kernels didn't compile because of the same problem with the "div" instruction. I followed your suggestion, and used _XMath.Rcp()_ as a workaround.
I had two other compilations problems :

```
        private static void Kernel2(GroupedIndex index, ArrayView<float> inArray, ArrayView<float> outArray)
        {
            var cachedValue = new float[4];
            for (int i = 0; i < 4; i++)
            {
                cachedValue[i] = inArray[i];
            }
            for (int i = 0; i < 4; i++)
            {
                outArray[i] = cachedValue[i];
            }
        }
```

```
        private static void Kernel3(GroupedIndex index, ArrayView<float> array)
        {
            byte b = 1;
            for (int i = 0; i < 2; i++)
            {
                if (b > 1)
                {
                    array[0] = 1;
                }
                b = 2;
            }
        }
```

For Kernel2, I found a workaround by unrolling the loops myself, and using unindexed variables (cachedValue0 to cachedValue3) instead of the array.
For Kernel3, the compilation problem disappear if I use an integer instead of a byte.

Now, my application is running ! Well, almost : the results are wrong, but I need time to investigate why. It can be an error introduced by the migration process.
The good news is that the performances are about identical to ILGPU 0.3, so they are very good!

**Comment by samy2** [comment]
Hi,
I investigated more concerning the "wrong results" I am observing.
One of the problem I found is concerning shared memory :

```
        [Test]
        public void Kernel4Test()
        {
            using (var context = new Context())
            {
                using (var gpu = new CudaAccelerator(context, 0))
                {
                    var kernel = gpu.LoadKernel<GroupedIndex, ArrayView<float>>(Kernel4);
                    var gpu_array = gpu.Allocate<float>(1);
                    kernel(gpu.DefaultStream, new GroupedIndex(1, 2), gpu_array);
                    var result = gpu_array.GetAsArray(gpu.DefaultStream);
                    Assert.AreEqual(1f, result[0]);
                }
            }
        }

        private static void Kernel4(GroupedIndex index, ArrayView<float> array)
        {
            ref var sharedMemory = ref SharedMemory.Allocate<float>();
            var threadIndex = index.GroupIdx;
            if (threadIndex == 1) sharedMemory = 1f;
            ILGPU.Group.Barrier();
            if(threadIndex == 0) array[0] = sharedMemory;
        }

        private static void Kernel5(GroupedIndex index, ArrayView<float> array)
        {
            var sharedMemory = SharedMemory.Allocate<float>(1);
            var threadIndex = index.GroupIdx;
            if (threadIndex == 1) sharedMemory[0] = 1f;
            ILGPU.Group.Barrier();
            if(threadIndex == 0) array[0] = sharedMemory[0];
        }

```
Kernel5 is working as expected, but Kernel4 is not (result is 0 instead of 1)

**Comment by m4rs-mt** [comment]
@samy2 I've been investigating your problems. Array example: Arrays are reference types and are currently not supported on any device. However, in 0.6 I will add limited support for class types.

The byte example cannot be compiled due to a problem in the PTX code generator. This problem applies to `byte` and `sbyte` types. Workaround: Use `short` or `ushort` at the moment.

Regarding your shared memory example: This was a memory (load/save) optimization pass problem. It simply eliminated the shared memory allocation node in favor of registers. Will be fixed in the next version.

**Comment by samy2** [comment]
According to my tests, the shuffle operations are working juste fine.
But the "width" parameter is no more available for theses operations. Is it intended ?

**Comment by m4rs-mt** [comment]
@samy2 Yes, that is correct. I removed these versions because they (currently) cannot be mapped 1:1 to AMD-specific SPIR-V statements, and I'm not sure they will be. This is especially interesting as we want to add Vulkan-Compute support in one of the next versions.

**Comment by samy2** [comment]
@m4rs-mt 
I understand your point. Adding Vulkan Compute support will be a very nice.
But the fact that different hardware supports different features/capabilities is a reality. Does-it mean that we should restrict the API to the least common denominator ? (By the way, Warp shuffle operations are only supported by NVIDIA devices of compute capability 3.x or higher. Should we remove all shuffle operations to be compatible with older devices ?)
My main concerne it that today, ILGPU 0.3 support theses operations, so, it is a kind of "regression" for users that use them today. Will they be stuck to ILGPU 0.3 ?
Wouldn't it be possible to re-introduce theses operations, in a way that make it clear that they are only supported on CUDA (and CPU) devices ? (Maybe with a special naming, or introduce the concept of "extensions" that are not compatible with all devices) ?

**Comment by m4rs-mt** [comment]
@samy2 Of course there are (totally) different hardware capabilities out there; but I get your point. My intention was not to completely remove them, but to integrate them so that users (or ILGPU?) can distinguish between "generic" and "specific" features.
We could re-introduce these instructions and add the concept of "accelerator capabilities" (or the like) and tag these commands with additional attributes and additional remarks. The ILGPU compiler could automatically deduce the required "capabilities" by analyzing the kernels, and the ILGPU runtime can check whether a kernel is compatible with an accelerator or not.

**Comment by samy2** [comment]
> We could re-introduce these instructions and add the concept of "accelerator capabilities" (or the like) and tag these commands with additional attributes and additional remarks. The ILGPU compiler could automatically deduce the required "capabilities" by analyzing the kernels, and the ILGPU runtime can check whether a kernel is compatible with an accelerator or not.

That would be great!
