### ISSUE TITLE
Struct does not support properties of bool type？

### ISSUE THREAD

**Issue by xxl-cc** [m4rs-mt/ILGPU#814]
i  testing SimpleStructures demo and i added the property of bool type in the CustomDataType .

throw System.NotSupportedException:“Type type 'SimpleStructures.Program+CustomDataType' is not blittable”

**Comment by MoFtZ** [comment]
hi @xxl-cc, unfortunately, this is a limitation that you will need to deal with manually. For example, you could use `byte` (blittable) instead of `bool` (not blittable). ILGPU requires that structs are blittable.

> These types are called blittable types because they do not require conversion when they are passed between managed and unmanaged code

The .NET [documentation on blittable](https://docs.microsoft.com/en-us/dotnet/framework/interop/blittable-and-non-blittable-types) states that `bool` is not blittable. This is because it `Converts to a 1, 2, or 4-byte value with true as 1 or -1.`
