### ISSUE TITLE
Is AcceleratorStream thread-safe?

### ISSUE THREAD

**Issue by Ruberik** [m4rs-mt/ILGPU#828]
If I have AcceleratorStream `stream`, can I launch a kernel from thread `A` on `stream`, and launch  another kernel from thread `B` on `stream`, and those two kernels will execute (in one order or the other) without there being thread safety issues?

Thanks in advance.

**Comment by MoFtZ** [comment]
hi @Ruberik, ILGPU makes use of the low-level CUDA Driver API. For the most part, this API appears to be thread-safe. There are a [few exceptions](https://docs.nvidia.com/cuda/cuda-driver-api/graphs-thread-safety.html#graphs-thread-safety), but ILGPU does not currently expose this functionality.

Note that if you have multiple threads adding kernels to the same stream, you might have difficulty identifying when each kernel ends. This is because calls like `GetAsArray1D` will internally call `stream.Synchronize`, which will block until both kernels finish.

**Comment by Ruberik** [comment]
Fine by me. Thanks, @MoFtZ.
