### ISSUE TITLE
Is non-thread-blocking async possible?

### ISSUE THREAD

**Issue by ugumba** [m4rs-mt/ILGPU#925]
Hi - great library!
I was a bit surprised to not find any "async" methods in the API.
If my CPU thread is only waiting to synchronize, I'd want to do it asynchronously (without blocking the thread).

That is, except for the abomination :-) `Task AcceleratorStream.SynchronizeAsync() => Task.Run(synchronizeAction);`, which is pointless - it only starts a new thread which waits synchronously, so that your current thread can pretend to be asynchronous.

This will certainly be an issue in applications which are *both* CPU and GPU intensive - blocked threadpool threads can be disastrous.
Is there something I'm missing?

**Comment by MoFtZ** [comment]
hi @ugumba, my understanding for why there is no `SynchronizeAsync` method in ILGPU is due to interacting with an external GPU device. ILGPU currently provides support for Cuda and OpenCL accelerators, and is reliant on the underlying Driver APIs provided by these technologies.

When a kernel is "launched", ILGPU will issue a command to the GPU to run the kernel - control will be returned to the CPU as soon as possible. The call to `Synchronize` will cause the CPU to block and wait for the GPU to complete any previously issued commands.

A hypothetical `SynchronizeAsync` call is not possible because the Driver APIs do not provide a mechanism for the GPU to signal that it has completed (via interrupts or other callbacks). Without the ability for the GPU to "push" a signal, the only remaining option is to "pull" the status from the GPU, by making a blocking call, or making a polling call.

**Comment by ugumba** [comment]
Thanks for the great explanation - if the drivers do not provide it, the current state makes sense.
