### ISSUE TITLE
Cuda accelerator incorrectly handles NaN comparison

### ISSUE THREAD

**Issue by MoFtZ** [m4rs-mt/ILGPU#93]
When using a simple kernel, and supplying `NaN` as an input value, the Cuda accelerator incorrectly compares `NaN` and returns `2.0` rather than `4.0`.

NB: The comparison `value == 0.0` can be changed to another number with the same/incorrect result on Cuda.
```
internal static void TestKernel(Index1 index, ArrayView<double> input, ArrayView<double> output)
{
    var value = input[index];
    if (value == 0.0)
        output[index] = 2.0;
    else
        output[index] = 4.0;
}
```

Full sample:
[ZeroOneNaN.zip](https://github.com/m4rs-mt/ILGPU/files/4572667/ZeroOneNaN.zip)

**Comment by m4rs-mt** [comment]
@MoFtZ Yes, you are right. `NaN`s will not be handled correctly in these cases. We have to extend the `PTXCodeGenerator` in a way that it supports proper `NaN` comparisons. However, we should avoid expensive `NaN` checks when the `ContextFlags.FastMath` flag is present.

**Comment by MoFtZ** [comment]
I looks like the issue occurs when the ILGPU runtime inverts the comparison - it detects a unary `not` combined with `equals`, and it inverts the comparison into a single `not equals` comparison.

The runtime currently uses `setp.eq.f64`, which according to [the documentation](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#floating-point-comparisons), already performs the `NaN` checks.

**Comment by m4rs-mt** [comment]
I have to admit that my comment was a bit misleading 😄 . It should be sufficient to emit "unordered" floating point comparisons without the need for additional `if`s according to the PTX specification. Currently, all comparisons assume "ordered" floating point semantics without paying attention `NaN` values. My question regarding performance was whether the "unordered" operations will be lowered to "slower" (or more expensive) SASS instructions in the end and should be avoided in fast-math mode.

However, the problem is a bit more sophisticated than that I think. First of all, the PTX backend does not pay attention to the "unordered" flag of all comparison operations. Furthermore, the CIL instruction `ceq` seem to have "ordered" semantics (returns `0` if any of the operands is not ordered). That's why the logical not operation will not update any "unordered" flag and the final comparison seems to be "ordered" (currently).

**Comment by MoFtZ** [comment]
thanks @m4rs-mt. Yes, I keep forgetting that PTX is yet another abstraction on top of SASS instructions.

I've put up a PR to try and fix this issue. Note that I haven't checked the SASS that gets generated when FastMath is turned on. Will take a look when I next have some free time.

**Comment by MoFtZ** [comment]
OK, so looking at the SASS file on my machine (GTX 1070):
* the call to `setp.ne.f64` translates to `DSETP.NE.AND`
* the call to `setp.neu.f64` translates to `DSETP.NEU.AND`

**Comment by m4rs-mt** [comment]
I made several measurements on 980TI, 1080TI, 2080S and a Tesla V100 and couldn't spot significant performance differences so far.
