### ISSUE TITLE
OpenCl codegeneration problems

### ISSUE THREAD

**Issue by AlexBatsev** [m4rs-mt/ILGPU#94]
I was very happy to observe that after my code became compilable and runnable on the CPU accelerator, it took me no effort to switch to Cuda -- no compilation errors, absolutely identical numerical results. But when I tried OpenCL, things went completely wrong. Maybe some of these problems are known and fixes are under development or planned for, but I’ll list them just in case. The C# source code is attached as [Empty.zip](https://github.com/m4rs-mt/ILGPU/files/4583239/Empty.zip), these files can be directly copied e.g. to ILGPU.Samples.Empty project. Kernel listed there does not compile due to numerous errors in the generated OpenCL source code, which is attached in [OpenCL_source.zip](https://github.com/m4rs-mt/ILGPU/files/4583270/OpenCL_source.zip) along with the error log from OpenCL compiler. I’ve added a preamble with stubs for OpenCL-specific keywords and functions, such that OpenCl_source.cpp can be added to some C++ project and inspected there comfortably. Here is the list of issues.

- Referencing non-existing fields in structs, e.g. `var94.field_9` while a struct `var94` has only 5 fields.
- `atomic_fetch_add` is missing. Indeed, OpenCL for some strange reason does not have atomic operations for floats, only integers. There are some custom implementations of atomAdd, though, like this one. http://suhorukov.blogspot.com/2011/12/opencl-11-atomic-operations-on-floating.html
- `Dynamic shared memory allocations are not supported by this accelerator` thrown by another kernel which is not in the attachment. Fortunately, OpenCl supports this feature: https://stackoverflow.com/questions/8888718/how-to-declare-local-memory-in-opencl

Inspection of generated source shows very inefficient private memory usage, even the simplest kernel may cause registers spilling as there are no code blocks in the generated code. All one can do is to pray that the compiler is intelligent enough to track variables lifetime and reuse registers. But there are so many OpenCl implementations out there… There is definitely room for improvement of codegeneration, especially taking into account that some patterns are very obvious and straightforward to implement (variables inlining, `if` blocks etc.).

Another simple improvement would be to extend the max allowed numer of kernel arguments. It took me some efforts to shrink all of them to 15 pieces.

**Comment by m4rs-mt** [comment]
@AlexBatsev Thank you very much for your detailed bug report. I am going to have a closer look 🔢

> Referencing non-existing fields in structs, e.g. var94.field_9 while a struct var94 has only 5 fields.

This seems to be serious bug; going to fix this.

> atomic_fetch_add is missing

ILGPU has software implementations for all possible atomic operations using a [similar algorithm](https://github.com/m4rs-mt/ILGPU/blob/master/Src/ILGPU/Atomic.cs#L264). However, there are some intrinsic-implementations missing in the final lowering phase. They will be added in the future and the problem should disappear.

> Dynamic shared memory allocations are not supported by this accelerator 

Absolutely; some of the features are not there yet since they have not been implemented so far 🤓 That's why the CL backend throws `NotSupportedExceptions` to notify the programmer in such a case. However, this does not mean that these features are not supported by OpenCL.

It's good to see that someone would use dynamic shared storage in combination with OpenCL. No feature requests have been made yet. I will mark this as an upcoming feature that will be available in v0.8.1.

**Comment by m4rs-mt** [comment]
@AlexBatsev are you using `beta2` or `beta3` currently?

**Comment by m4rs-mt** [comment]
@AlexBatsev I was slightly confused about the comments regarding private memory since ILGPU performs several code transformations and SSA construction to get rid of "slow" `alloca` nodes that require memory to be explicitly allocated on the stack. You are essential referring to the fact that variables are not "inlined" and simple if blocks etc. are not converted into predicated operations. There has been much work related to the PTX backend (see #70) to overcome most of these limitations and to emit code in such a way that the driver emits the "desired" pieces of code (ILGPU essentially mimics the Cuda compiler).

> There is definitely room for improvement of codegeneration, especially taking into account that some patterns are very obvious and straightforward to implement (variables inlining, if blocks etc.).

Definitely 🤓 We will definitely improve the OpenCL backend in the future to emit nicer code. In particular, some of the drivers are sometimes confused about `goto` statements and emit "better" (in terms of performance and even register usage...) code if they encounter `if` and `while` statements. This is another thing that we could potentially take into account when polishing the OpenCL backend.

**Comment by AlexBatsev** [comment]
@m4rs-mt, Thank you for a comprehensive answer. It occured to me that many of the bugs and problems which may prevent someone from using OpenCl with ILGPU can be overcome by giving a possibility to use handwritten kernels instead of auto-generated. Personally, I’d be happy to use such a short-cut to OpenCL. 
The workflow here could be that I take the auto-generated code, leave only declarations of structs and kernels, and substitute the kernels’ bodies by my own code in efficiency and correctness of which I’m sure. To that end, I certainly shall need to understand the purpose of all auto-generated kernel’s arguments (their number is approximately a double of ones from the initial C# method), so some micro-description is needed. After that I call another overload of `LoadAutoGroupedStreamKernel` which accepts a string with a custom OpenCL code. I understand that auto-generated kernels' declarations are in a way implementation details and could be quite volatile. Still, I’d prefer to use them at my own risk rather than not to have such a possibility at all.
@m4rs-mt, what do you think about this?

**Comment by AlexBatsev** [comment]
I'm using beta2.

**Comment by AlexBatsev** [comment]
@m4rs-mt. 
Regarding private memory, I simply meant that there are too many redundant stack variables which are extremely short-living, and there are no code blocks which may help the compiler to reuse registers. But I’m pretty sure you know this shortcomings (if they are shortcomings really) better than me.

**Comment by AlexBatsev** [comment]
Small question. Now, in order to use some struct in a kernel, it needs to be declared as a public, otherwise a TypeLoadException will be thrown by ILGPU. But I don’t want to contaminate the public API of my dll by making such private structs visible from outside. Is there any workaround for this situation?

**Comment by m4rs-mt** [comment]
@AlexBatsev You can declare all types to be `internal`ly visible. You can use an [assembly attribute](https://github.com/m4rs-mt/ILGPU.Samples/blob/master/Src/AdvancedViews/AssemblyAttributes.cs) to allow the ILGPU runtime access to internal types and methods.

**Comment by m4rs-mt** [comment]
> Regarding private memory, I simply meant that there are too many redundant stack variables which are extremely short-living

Yes, I totally agree. We will change this in one of the upcoming OpenCL backend versions 🔢

**Comment by AlexBatsev** [comment]
@m4rs-mt. Your advice works, thank you! Before, I was trying to fix the problem by using `[assembly: InternalsVisibleTo("ILGPU")]`, but that was obviously insufficient.

**Comment by m4rs-mt** [comment]
@AlexBatsev Sorry for the late response; I accidentally missed to answer your post.

> Thank you for a comprehensive answer. It occured to me that many of the bugs and problems which may prevent someone from using OpenCl with ILGPU can be overcome by giving a possibility to use handwritten kernels instead of auto-generated. Personally, I’d be happy to use such a short-cut to OpenCL.

One of ILGPU's goals is to avoid writing a kernel in a "different" programming language and to focus on you favorite .Net-compatible language (including its semantics and specialties) to write platform-independent code that can be easily debugged and deployed across a huge variety of different targets. However, I get your point. As long as there are "serious" issues with respect to OpenCL it might make sense to have the opportunity to "manually tweak" the resulting code. Unfortunately, this does not work properly when it comes to PTX or SPIR-V. We are always focusing on the correctness and the performance of the code being generated in the first place. However, most industrial users that leverage ILGPU in the scope of their products (or even researchers at the DFKI) target Cuda-enabled GPUs first. That's why the OpenCL backend must still be considered to be highly experimental. Another issue with OpenCL is the generation of source code in general. As I previously mentioned, ILGPU has never been designed to emit source code and that's why the OpenCL backend is an intermediate solution until a SPIR-V backend is available 🔢 

> The workflow here could be that I take the auto-generated code, leave only declarations of structs and kernels, and substitute the kernels’ bodies by my own code in efficiency and correctness of which I’m sure. To that end, I certainly shall need to understand the purpose of all auto-generated kernel’s arguments (their number is approximately a double of ones from the initial C# method), so some micro-description is needed. 

One of the reasons for adding additional kernel arguments is the fact that every view is passed separately to work around several driver and specification limitations. Not related to the number of arguments (but important to know) is the fact that structures are flattened and do not reflect their original nesting information any more.

> After that I call another overload of LoadAutoGroupedStreamKernel which accepts a string with a custom OpenCL code. I understand that auto-generated kernels' declarations are in a way implementation details and could be quite volatile. Still, I’d prefer to use them at my own risk rather than not to have such a possibility at all.

This is possible (but ugly) using a `LoadKernel`  overload while passing an instance of a `CompiledKernel` object to it. You can "manually" generate OpenCL source code and create an instance of a `CLCompiledKernel` class reflecting the compiled kernel source code. However, ILGPU assumes that there is a managed function to resolve more information about all parameters from.

**Comment by m4rs-mt** [comment]
We have implemented all features that were previously missing. I will close this issue for the moment.
