### ISSUE TITLE
Integration with current app

### ISSUE THREAD

**Issue by ilkerccom** [m4rs-mt/ILGPU#990]
Hello,

I have an application that is currently running with CPU. How can I make it GPU supported? I want it to do the calculations on the GPU. Or there may be a code sample that will generate a random private key and convert it into a BTC address.

I have read the guide and documentation but I do not understand it.

Project example; https://github.com/ilkerccom/bitcoinpuzzlescanner

Thanks.

**Comment by MoFtZ** [comment]
welcome @ilkerccom. We have [code samples](https://github.com/m4rs-mt/ILGPU/tree/master/Samples), but nothing specific for your needs.

Looking at the example project you linked to, it will unfortunately need to be re-written as there are a number of limitations with GPU programming. For example, `BigInteger` is not supported on the GPU because it is not possible to perform memory allocations inside GPU kernel. Another example of a limitation is the inability to perform `string` handling, such as `string.Format` or `BigInteger.Parse`.

You might want to start with reading the ILGPU documentation, which has some beginner tutorials - https://ilgpu.net/docs

We also have a [Discord server](https://discord.gg/X6RBCff) that you might like to join.

**Comment by ilkerccom** [comment]
Thanks @MoFtZ, I will review the documentation again.
